### ISSUE TITLE
Mapping of parallel element instructions 

### ISSUE THREAD

**Issue by mjmascaro** [rbms-bsc/DCRMR#10]
In DCRM(B), outside of area 1, instructions for recording parallel statements (e.g., parallel statements statements) start out with explaining if an element appears in multiple languages or scripts, which one to record in the element proper and before going into instructions for how to record the parallel statement.
 
Example:
DCRM(B) 6C1.
If the source bears a series title in more than one language or script, transcribe as the series title proper the title that is in the language or script of the title proper. If this criterion does not apply, transcribe the title that appears first in the source. Transcribe the remaining title(s), together with any associated information, as parallel series titles. Precede each parallel series title by an equals sign. Make a note to indicate the original position on the source of any transposed titles.

General during the rewrite assignment, editors have been moving the instructions on how to select the element proper to that element.  

Example:

[Title of series](https://docs.google.com/document/d/1AMJZw6ygj9OMp4flMwLbnrrTLQMuiSa1gn66z_weVlg/edit#bookmark=id.a1swmb5c1ucx)
If the source bears a series title in more than one language or script, transcribe as the series title the title that is in the language or script of the title proper. If this criterion does not apply, transcribe the title that appears first in the source. Transcribe the remaining title(s), together with any associated information, as parallel series titles.

[Parallel title of series](https://docs.google.com/document/d/1fbkzJv1ygRo6-LzmtoUqinz2qw58DVbfqXDN2lixYkM/edit#)
Transcribe series title(s) in another language or script, together with any associated information, as parallel title of series. Make a note to indicate the original position on the source of any transposed titles. See note on series statement.

Different approaches have been taken for how to word the parallel element instruction in different sections,  

Another example:

[Parallel name of manufacturer](https://docs.google.com/document/d/1k3Wl9uO1X-AF-zINvdBaVpILHLfDavvRLpWAnWzZ8os/edit#)
Take parallel manufacturers’ names from the same source as the manufacturer’s name. Make a note on parallel manufacturers’ names found elsewhere if considered important for identification. See Note on manufacture statement.

Questions:
1. Do we wish to parse the DCRM(B) original instructions this way?

2. What model should we use for parallel element instructions?

3. If we do break up the instruction, should a reference be added from the parallel element instructions to the instruction in the element proper describing how to select the element proper when it appears in multiple language or scripts?

**Comment by flapka** [comment]
To @mjmascaro 's questions:

3. Rather than rely only on a link back to the element proper (the non-parallel bit), my preference is that all of the parallel elements can be thought of as instructions where guidance is repeated (for the most part) in multiple places. 

2. If we do enact repeated instructions, the guidance in parallel title of series could appear something like:

If the source bears a series title in more than one language or script, treat as [title of series](https://docs.google.com/document/d/1AMJZw6ygj9OMp4flMwLbnrrTLQMuiSa1gn66z_weVlg/edit#bookmark=id.a1swmb5c1ucx) the title that is in the language or script of the title proper. If this criterion does not apply, treat the title that appears first in the source as [title of series](https://docs.google.com/document/d/1AMJZw6ygj9OMp4flMwLbnrrTLQMuiSa1gn66z_weVlg/edit#bookmark=id.a1swmb5c1ucx. Transcribe the remaining title(s), together with any associated information, as parallel title of series.

**Comment by mjmascaro** [comment]
Determined this is somewhat dependent on the outcome of issue #11

**Comment by mjmascaro** [comment]
Decided to continue to use parallel elements in DCRMR at [June 17, 2020 editorial group meeting](https://docs.google.com/document/d/11a55GuLkWWEFBg8MiQPBnuQI_pw989Tbne8nX0zNmgo/edit?usp=sharing).

**Comment by mjmascaro** [comment]
Iris brought to my attention that while the decision had been made to continue to use parallel elements, we did not circle back on the discussion on whether to repeat the guidance in the parallel element instructions on how to select what to record in the element proper versus parallel elements.  Taking liberty of reopening ticket.

**Comment by ladylazarus3** [comment]
i don't know if this helps, but here is what i did when i was "experimenting" with filling out the parallel elements for the chapter 4 entities.  [parallel place of distribution](https://rbms-bsc.github.io/DCRMR/books/ppdm/Parallel-place-of-distribution/) and [place of distribution](https://rbms-bsc.github.io/DCRMR/books/ppdm/Place-of-distribution/#4.211.995.1).

The instructions tend to repeat themselves a bit, but it makes sense to have the instructions in both places where they apply to both entities.  Is this along the lines of what other folks were thinking too?

kalan

**Comment by mjmascaro** [comment]
That mock up was very helpful @ladylazarus3 .  Seeing this I am for repeating the guidance in both elements.

**Comment by ladylazarus3** [comment]
Sure thing, @mjmascaro . :)  This repeated guidance in parallel elements mirrors this mocked up experimentation with the [various entity instructions](https://rbms-bsc.github.io/DCRMR/books/ppdm/Parallel-place-of-publication/#4.202.3.2) and their [corresponding notes](https://rbms-bsc.github.io/DCRMR/books/ppdm/Note-on-publication-statement/#4.206.7.1).  The note pages get a bit lengthy, but i like that it collocates all the different types of notes that can be made per entity in one place.  This is handy when training new folks, spot checking all relevant notes indeed did make it into the description, and serves a similar purpose to the listing of required notes in the index of DCRM(B).  (i haven't started work on an index for DCRMR yet-- i'm not sure that an index has been discussed yet, but the glossary is working and ["how to" documentation](https://github.com/rbms-bsc/DCRMR/wiki/How-to-populate-a-new-Glossary-Page) and a [glossary page template](https://github.com/rbms-bsc/DCRMR/wiki/Template:-Glossary-Page-Template-for-DCRMR) has been made).

Also, on the chapter pages for [other notes](https://rbms-bsc.github.io/DCRMR/other-notes/) and [notes on items](https://rbms-bsc.github.io/DCRMR/notes-on-items/) we could potentially add xrefs to some of the notes included in other chapters, just so if folks expect to find them in the "notes" chapters, they would find them in both places with a helpful redirect to their official location within the text (i.e. being organized with the entities they are notes about).

**Comment by elizhobart** [comment]
Thanks for the example, kalan. It seems like repeating these instructions is useful, for the reasons you mentioned. I think it would be worth discussing with the larger group and make sure that we're all on the same page. I will schedule this for our next meeting.

**Comment by lizoknj** [comment]
It helps to see how this plays out in GitHub. I vote for repeating the instructions in the main element and in the parallel element.

**Comment by elizhobart** [comment]
Decision in July 29 meeting: repeat instructions in the main element and parallel element.
