### ISSUE TITLE
Transcription - instruction at 0.5.94.6

### ISSUE THREAD

**Issue by rarebkcat** [rbms-bsc/DCRMR#108]
In the section on [Transposition (0.5.94)](https://rbms-bsc.github.io/DCRMR/general-rules/Transcription/#0594-order-and-transposition), there is the following instruction at [0.5.94.6](https://rbms-bsc.github.io/DCRMR/general-rules/Transcription/#0.5.94.6):
 
> If information appears in scattered form on the preferred source of information but no transposition is needed and information about the specific placement of the scattered information is considered important for identification then make a note to indicate the placement.
 

> Example:
> The country twenty five miles round New York / drawn by a gentleman from that city ; J. Barber, sculp., Holborn Hill.
> Note on statement of responsibility: Engraver statement appears in bottom right corner of map.
> (Comment: Information is transcribed in two elements: Title proper and Statement of responsibility.)

Link to example: [The country twenty five miles round New York](https://www.loc.gov/resource/g3804n.ar109600/?r=0.294,0.372,0.687,0.311,0)
 
We have two questions: 1. Do we retain this instruction? 2. If we retain this instruction, should we add an example from a books context, such as a artist’s book or modern poetry broadside if possible?
 
1. Do we retain this instruction?
 
Transcription, based on RBMS PS text, is largely an integrated text. Instructions that cause confusion or pertain solely to a single manual may have been removed (for example, Key Designations is in the Future Work issue).
 
We are concerned that this instruction, which originally came from DCRM(C), may be one that causes confusion and, therefore, ought to be omitted at this time. Is this scenario already covered by 0.5.92.5? Information is always presented in a specific order on a printed title page or a printed single sheet. If information is "scattered" on a printed title page or a single sheet and not in the order expected, you would apply [0.5.92.5](https://rbms-bsc.github.io/DCRMR/general-rules/Transcription/#0.5.94.5) because you would have to transpose the information and make a note about the transposition. It's the phrase "no transposition is needed" in this second instruction that we find problematic because it might only apply to maps or graphics where there is no specific order to the sheet.
 
However, it could also potentially apply to some artists’ books and modern poetry broadsides, which are cataloged as books but really straddle the line between textual and visual resources. 
 
With all of that in mind – do we want to retain the instruction?
 
2. Examples for 0.5.92.6
 
If we do retain the instruction, should we add in an example that more clearly pertains to monographs cataloging, such as from an artist book or modern poetry broadside (if possible)? 
 
If so, does anyone have any suggestions? 
 
(Our other thought was to reach out to the group that was going to present the cataloging artists’ books workshop.) 
 
<u>Context for transcription</u>: when I pulled the section on Transcription together, I followed the RBMS PS, which was an integrated set of instructions that included the decisions of the DCRM(B) for RDA Revision Group (2012-2014) and the DCRM-RDA Task Force (2014-2017); I read it against DCRM manuals, largely DCRM(B) and DCRM(G), to create the hierarchy and to look for omitted instructions. Iris, Michelle, and I have been working as a small group to iron out some of the last hiccups, and there are a few issues, such as this one, we wanted to bring to the group.

**Comment by dcrmr** [comment]
Decision made in Editorial Group meeting, September 28: Retain the instructions, as it will be useful for catalogers describing books. For now, retain the cartographic example, but we will also want to add a book example.
