### ISSUE TITLE
Transcription - Transposition

### ISSUE THREAD

**Issue by rarebkcat** [rbms-bsc/DCRMR#112]
**Background / Context**

At the Feb. 18, 2020 meeting, we decided to “Retain instructions regarding order of elements and transposing elements; will revisit at later date” (see DCRMR Editorial Guidelines, [Principles of content](https://github.com/rbms-bsc/DCRMR/wiki/DCRMR-Editorial-Guidelines#principles-of-content)). 

The instructions 0.5.94.1 - 0.5.94.7 in Order and transposition come from [RBMS PS 1.7.16](https://docs.google.com/document/d/1b2ORJRR6YNnUVMZEGXPBZpt0tsTVpatQmZahsRgJSK8/edit#heading=h.svs77cpfytgf). 

However, there is a larger question about what transposition means in an atomized, element-based environment. Instructions about transposition occur throughout our instructions and carry meaning for us, but the text often doesn’t define in great detail what it means to be transposed – ISBD and the order of DCRM(B) itself did that work – and the details of instructions given vary. 

When working on Transcription, Michelle, Iris, and I felt like we should try to explain what’s ‘expected’ so that we can help people understand what’s ‘transposed.’ We felt that this is especially important as newer catalogers may be increasingly less familiar with ISBD areas and order and as we move further from an ISBD-based standard. 

Therefore, we drafted two things to contextualize Transposition:

[[Introduction for Order and transposition] 0.5.94.05](https://rbms-bsc.github.io/DCRMR/general-rules/Transcription/#0.5.94.05)  
This is a general introduction to order and transposition, including a list of commonly used elements, and talking about what we mean when we say, for example, that a statement of introduction is transposed when it precedes the title proper on the preferred source of information.

[Transposition – extended instructions](https://docs.google.com/document/d/18ubJkfre2Zk-VSoazpmRm1eyFhP17nuxZIQkSOmSI68/edit)
This is a detailed introduction to the expected relative order of elements created by reading DCRM(B) and ISBD. Please note that it was drafted last week, and it hasn’t been thoroughly proofread yet. 

Drafting it did highlight some of the complications with transposition instructions when placed in atomized element instructions. For example, instructions about statements of responsibility when there are parallel titles pertain to both statement of responsibility elements and parallel statement of responsibility elements; however, they are present in the instructions for parallel statements of responsibility ([2.21.3](https://rbms-bsc.github.io/DCRMR/sor/Parallel-statement-of-responsibility-relating-to-title-proper/#2213-statements-of-responsibility-following-titles-in-more-than-one-language-or-script), [6.23.3](https://rbms-bsc.github.io/DCRMR/series/Parallel-statement-of-responsibility-relating-to-series/#6263-parallel-statement-of-responsibility-relating-to-series)).

**Questions**

Is this – the text at 0.5.94.05 and/or the text at “Transposition – extended instructions” – a good way to give an overview of order and transposition? Do we retain either or both of these additions?

If we think “Transposition – extended instructions” is useful, where should the text go?

We came up with three options:

In Transcription, immediately following 0.5.94.05. You can see a draft of what this would look like in context at the [bottom of the Transcription – extended edition gdoc](https://docs.google.com/document/d/18ubJkfre2Zk-VSoazpmRm1eyFhP17nuxZIQkSOmSI68/edit#bookmark=id.rm7qu7aksyn7) draft
* Pro: It keeps all of the transposition text together unless it’s within a specific element
* Con: It’s a lot of text. Additionally, it gets quite far into the weeds – do we want that on a General Rules page?

On the chapter pages	
* Pro: Structurally, Transcription -> Chapter pages -> Element pages is a nice narrowing of scope. Transcription lays out the order on the Area level, with a few details; chapter pages cover the elements within the chapter; element pages include specific examples and, if applicable, additional instructions. It addresses some of the complications re: transposition instructions applying to multiple elements within a chapter. Finally, it matches the way we put “Source of information” on the chapter pages.
* Con: It’s a third location of information related to transposition. Additionally, Chapter 1: Title and Chapter 2: Statement of Responsibility will need some sort of cross-reference, as they’re intertwined. (Perhaps put the instructions for Area 1 on the Chapter 1: Title page and point people to it from the SoR chapter page?)

On a separate page (perhaps combined with Prescribed punctuation?)
* Pro: puts ISBD stuff together (we would need to change the title of the Prescribed punctuation page)
* Con: Adds a third location of instructions that doesn’t follow the general to specific pattern of putting it on the chapter pages, and might require further click throughs. Also, transposition is integral to instructions whereas prescribed punctuation is an agency-level decision.

**Comment by rarebkcat** [comment]
I increasingly think I like the extended transposition instructions on the chapter pages. I'm a fan of the structure of it, and how covers the relationships of multiple elements within the chapter. It feels a bit in the weeds to be on the General Rules / Transcription page. 

I take @jess-grz's point (made at our meeting and hopefully accurately paraphrased!) about it being very ISBD-based content to be in the main text, but... well, it is ISBD content, and it's throughout the element pages, so I'm okay with that. I feel like transposition is so integrated within the element instructions, albeit unevenly, that pulling it out to go with, for example, prescribed punctuation wouldn't be my preference.

**Comment by jess-grz** [comment]
I like this direction @rarebkcat and I agree that we wouldn't want to isolate it in the General Rules. Putting the whole text of the extended transposition instructions in the prelim section seems to elevate ISBD instructions to a level that we're not really intending to. It's my preference to either place the extended rules for each group of elements on the appropriate chapter page (as is also your preference) or adding the whole extended instructions as an appendix. The advantage of the former approach is that instructions are more visible and digestible as you work through each element in a description, while the advantage of the latter is the ability to see more clearly the structure of an entire "record." In short, sounds good to me, @rarebkcat :)

**Comment by dcrmr** [comment]
Following GitHub discussion and discussion between the editor and keepers of the text, we will move forward with adding transposition information to chapter pages. Thank you for your work on this, @rarebkcat!
