### ISSUE TITLE
Required and optional access points for titles

### ISSUE THREAD

**Issue by deborahjleslie** [rbms-bsc/DCRMR#123]
We need a better of indicating when an [access point for a variant title](https://rbms-bsc.github.io/DCRMR/title/Variant-title-of-manifestation/#12535-access-points-for-variant-titles ) is optional or required. These were integrated from DCRMB Appendix F. In that appendix, it was explained that rules for title access were required unless marked optional, which was done by including (Optional) as part of the rule heading. 

Including (Optional) as part of the section title doesn't work well when the section titles are indexed. I propose that for each title access rule be indicated as required or optional, and that this be separated from the section title. Altough this is a different route than what we've taken for notes, I believe it is necessary for title access rules to be correctly understood and applied, especially since they have now been dispersed among several elements. I'm focusing on access points to variant titles because it is only here that (Optional) is used as part of the section title, but whatever we decide should be applied to all instructions relating to access points. 

One method would be to add a status category for the rule as part of each section, with or without a label. For example:

[1.25.352 Latin title proper with final capital I representing ii](https://rbms-bsc.github.io/DCRMR/title/Variant-title-of-manifestation/#125352-latin-title-proper-with-final-capital-i-representing-ii).
Required
1.25.352.1 If any of the first five words in the Title proper is a Latin word with a final capital I that has been retained in the transcription, provide additional title access for the form of title proper with the final capital I converted to ii (see 0.4.24).

[1.25.3555 Title proper with non-standard orthography](https://rbms-bsc.github.io/DCRMR/title/Variant-title-of-manifestation/#1253555-title-proper-with-non-standard-orthography-optional)
Optional
1.25.3555.1 If the Title proper contains words spelled according to older or non-standard orthographic conventions, provide additional title access for the title spelled according to modern orthography.)

If labels are desired, may I submit "Status:" or "Category:" as a starting point.

**Comment by dcrmr** [comment]
Decision from November 6 meeting: (optional) labels will be retained in titles. Required title access points will be marked (required). As part of the heading review, Deborah will note which are required and request these changes, which will be made by the keepers.
