### ISSUE TITLE
Language of supplied text

### ISSUE THREAD

**Issue by elizhobart** [rbms-bsc/DCRMR#124]
I'm noticing some inconsistency with language of supplied text. I've spotted four variations so far:

- Use an English form of the name (5.21.32.1)
- Use a modern English form of the name (5.21.325.1)
- Use the form of the name in the language preferred by the agency creating the data (5.21.36.3)
- Supply ... a phrase in the language and script of the cataloging agency (5.21.33.2)

I would like this to be more consistent, unless there's a reason to sometimes specify English and sometimes the language of the agency. My preference is "language and script of the cataloging agency," but want to get feedback from the group as a whole.

**Comment by deborahjleslie** [comment]
You have a good point, Elizabeth. I wonder if it would provide better guidance to point catalogers toward authorized forms of place names (whatever that authorized source is).

**Comment by elizhobart** [comment]
Suggestion: Modern form of name in the language of the cataloging agency.

**Comment by dcrmr** [comment]
Decision from November 6 meeting: Use phrasing "a modern form of the name in the language of the cataloging agency" instead of specifying English. This change will be made for all instructions related to recording place.
