### ISSUE TITLE
See also links to elements in RDA Toolkit

### ISSUE THREAD

**Issue by mjmascaro** [rbms-bsc/DCRMR#128]
There are several places within chapter 9 (Additional Notes) where DCRMR gives a see also reference to an RDA element related to access points, which we decided were out of scope for DCRMR proper.  In these cases, the link takes you directly to the element page in the RDA Beta Toolkit.  (Example [Note on sequential works](https://rbms-bsc.github.io/DCRMR/additional-notes/Note-on-work/#9132-notes-on-sequential-works).)  

The first time I clicked on one, I did a double take when I found myself in RDA versus DCRMR. I think these references are useful, and I think it would be good to do something to better designate that they are not to internal DCRMR elements.  Maybe something as simple as adding “in the RDA Toolkit” to the reference.  (Example “(see also [Succeeded by work](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-948e6981-db86-3738-bc36-6650ff6330f1) and [Preceded by work](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-e9b23ff8-cfc6-3a5a-a9ef-8019a8aaf1f0) in the RDA Toolkit)” .  

Thoughts?

**Comment by elizhobart** [comment]
I think “(see also Succeeded by work and Preceded by work in the RDA Toolkit)” will probably work. My one concern might be that a user might click the link without finishing the sentence and have the same double take (although that would be on them for not reading the whole sentence). An alternative might be to add "RDA:" or "RDA Toolkit:" before the link, similar to our [links to vocabularies in the RDA registry](https://rbms-bsc.github.io/DCRMR/phys-desc/Illustrative-content/#6223-general-rule).

**Comment by mjmascaro** [comment]
More I think about it, I like the alternative suggested.  An additional benefit for following that scheme for external links is if the domain ever changes on an external resource DCRMR links to frequently, it could make searching for all the links that need updating easier.

**Comment by elizhobart** [comment]
I hadn't thought of that additional benefit, Michelle! Since domains do change (as is about to happen with the entire Beta Toolkit), this would be a huge plus. The more I think about it, my preference would be for "RDA Toolkit." Since we also link to the RDA registry, specifying the Toolkit will be more clear.

**Comment by ladylazarus3** [comment]
one last thought from me on this as i am putting my socks on.  has anyone
heard whether or not the Beta Toolkit links will be automatically
redirected to the new site?  might be a maintenence issue for Toolkit
links...

**Comment by elizhobart** [comment]
I haven't heard, but I hope so! This also occurred to me recently, but figure we'll cross that bridge after December 15...

**Comment by lizoknj** [comment]
Belatedly agreeing with previous comments. I was taken aback the first few times I was hurled out of the warm and comfy environment of DCRMR into the remote fastnesses of the RDA Toolkit.  During the re-write phase of the project, we were supposed to use a different color for the hyperlink depending on its destination, but that won't meet accessibility requirements, and it is not as informative as using the string "RDA Toolkit" before the link.

**Comment by elizhobart** [comment]
Thanks, everyone. Let's go with adding "RDA Toolkit" before the link so that folks know they're about to be redirected.

Also, to clarify, the different link colors used in the re-write were more intended to be a flag to group members while we imported the text into GitHub, since internal and external links need to be coded slightly differently. Both display as blue text in GitHub.
