### ISSUE TITLE
No RDA element for certain types of physical description

### ISSUE THREAD

**Issue by lizoknj** [rbms-bsc/DCRMR#13]
(Discussed during the text finalization phone call on June 2)

For some types of physical description, there is no specific RDA element.

Examples (not an exhaustive list, I’m sure):
     details of colour content, details of illustrative content (these used to exist, but were eliminated from RDA)
     typeface (there are RDA elements for font size and for point size but not for font, i.e. typeface—something that might be addressed in the future, perhaps?)

The note on manifestation element and the note on carrier element are possibilities. In our discussion yesterday, Francis suggested that note on carrier was more suitable for information on materials, so it doesn't seem to fit. The  PS on note on manifestation (2.17.1.3)  included examples for color and for typeface, so this is where we were inclining during the first phase of DCRMR

     Text printed in roman type; side-notes.
     Title page printed in red and black. 

Another reason for preferring note on manifestation is that many notes on physical description include information on several different elements, so can't be recorded in a more specific element.
 
One other possibility: the RDA elements for color content and illustrative content have an option to record details or other unstructured information in an unstructured description. But this doesn’t seem helpful in the current cataloging environment (it would end up in a general note, anyway), so.. 

Any other thoughts?

**Comment by mjmascaro** [comment]
Since the BetaToolkit now has illustrative content and color content at the manifestation level versus the expression level (yay!) I agree that note on manifestation is the best fit for these notes.

**Comment by mjmascaro** [comment]
Agree at text finalizing group meeting June 8, 2020 that note on manifestation appears to be the best element.  Michelle confirmed after the meeting we've not be specifying source of information for note elements in DCRMR drafts.

For background, this changes of illustrative content being a manifestation level element (as shortcut relationship) and the removal of details of colour content and details of illustrative content happened in April 2020 update to the Toolkit.  This was an outcome of RSC discussions at the Santiago, Chile in October 2019 and its online meeting in January 2020  on RDA content elements in relationship to the treatment of aggregates.  

See [RSC/Minutes/Public/159-204](http://www.rda-rsc.org/sites/all/files/RSC-Minutes-Public-159-204.pdf) p. 25
[ RSC/Minutes/Public/205-214](http://www.rda-rsc.org/sites/all/files/Minutes%20Public%20January%202020%20meeting.pdf) p. 3

**Comment by mjmascaro** [comment]
At editorial group meeting on June 17, 2020, decided that mapping to note on manifestation results in these instructions appearing in the general note chapter and not in the physical description chapter which is problematic.
