### ISSUE TITLE
Capitalization in examples

### ISSUE THREAD

**Issue by elizhobart** [rbms-bsc/DCRMR#130]
In an email thread on November 16, a question was raised regarding capitalization in examples, noting some differences in practice:

5.01.3.2 - Distribution statement: London : Sold also by Vernor and Hood, Crosby and Letterman ($b capitalized)
5.01.3.3 - Distribution statement:  London: printed and published by C. Lowndes, No. 66, Drury-Lane; and sold by H.D. Symonds, Paternoster Row, 1800 ($b not capitalized)

In the email thread, we decided that we should not be agnostic regarding capitalization and that we should be consistent. A suggestion was made to capitalize every element, but this was not widely supported, as this has never been our practice and would be undesirable for some elements (e.g., other title information, date of publication, dimensions).

I propose that we format capitalization in examples using ISBD capitalization practices. This will give us a consistent appearance throughout the text and align our examples with past practice.

We will capitalize the first letters of:
- Title proper
- Alternative title
- Parallel title proper
- Edition
- Place of publication, distribution, manufacture
- Name of publisher, distributor, manufacturer (except for "publisher not identified")
- Series title
- Parallel title of series
- All notes

We will not capitalize the first letters of (except for proper names): 

- Other title information
- Parallel other title information
- Statement of responsibility (e.g., "by" instead of "By")
- Date of publication, distribution, manufacture
- Extent
- Dimensions
- Other physical details (300 $b)
- Other title information of series
- SoR related to series
- Series numbering

Does this look good to everyone? Is there anything we're missing?

**Comment by deborahjleslie** [comment]
Looks good.

**Comment by jess-grz** [comment]
Yes, I agree. This is in line with how the examples are presented in the DCRM suite, so it makes sense to continue in this way.

**Comment by elizhobart** [comment]
Thanks, everyone. @rarebkcat @ladylazarus3 is it okay with you both if I add this to the style sheet and then close the issue?
