### ISSUE TITLE
Normalized, nonnormalized, and basic transcription

### ISSUE THREAD

**Issue by deborahjleslie** [rbms-bsc/DCRMR#131]
Since two paragraphs on transcription in the current DCRMR draft contradict each other, this issue needs to be reviewed. 

> DCRMR normalizes punctuation and capitalization based on current conventions, with an optional exception in punctuation (see[ 0.4.31.5](https://rbms-bsc.github.io/DCRMR/general-rules/Transcription/#0.4.31.5)).
> 
> If nonnormalized transcription is considered important, follow [RDA Guidelines on basic transcription](https://beta.rdatoolkit.org/Guidance/Index?externalId=en-US_ala-fd2213e6-ae72-3e6f-8f0a-be3fc0e8d728) and consistently apply it throughout the resource description.

**Background**

‒	Rare book cataloging rules from BDRB on offer an original punctuation option—sometimes called double punctuation—in which the punctuation on the source is transcribed in addition to prescribed punctuation

‒	A few institutions employ it regularly, and projects as the ESTC employ a hybrid version which omits some prescribed punctuation, while the majority go with the standard instruction to normalize punctuation.

‒	RDA introduced instructions for "basic transcription," explicitly intended to [reduce the need for cataloger intervention](https://beta.rdatoolkit.org/en-US_ala-ad9f832e-c5c5-31f0-b928-2e860f8e4937). Basic transcription requires preservation of original punctuation AND capitalization.   

‒	The question on preserving original capitalization was raised [at a meeting](http://rbms.info/files/committees/minutes/2018/bibstandminutes18a.pdf) of the Bibliographic Standards Committee (page 27); follow-up on DCRM-L is [summarized here](https://docs.google.com/document/d/1rpG4rAit5rWYUQEr_DSscXrd7xVP6jymxe0NRs5P5ic/edit?usp=sharing).   

**Current questions**

‒	Discussion was primarily in the context of the original (pre-3R) Toolkit and has not engendered much public discussion. Does the current DCRMR editorial team still agree with this decision? Should we drop reference to RDA's guidelines to basic transcription?

‒	"Nonnormalized transcription" isn't defined anywhere. Should we revert to DCRM usage of "original punctuation"? 

‒	If memory serves, the RBMS-PS editorial team talked about and perhaps came to a consensus on requiring a note on the type of transcription employed. Although tedious to catalogers to always include a note, it would enable users of our records to interpret what they're looking at. 

‒	(The big question. Our successors will be happy to have this documented). What is the principle behind preserving original punctuation? Why would it not apply to preserving original capitalization?

**Comment by mjmascaro** [comment]
Deborah, thank you for bringing up the confusion here.  The definition of nonnormalized transcription did not make it over from the RBMS PS drafts.  Nonnormalized transcription is meant to be "take what you see transcription," so this is intended to be a seperate option for catalogers to preserve both captialization and punctuation.   Having this option was considered important by the RBMS PS editors.  However, during community review of the transcription PS (linked above), institutions that followed the current DCRM "original punctuation" alternative said they did not want recording original punctuation to be coupled with having to also perserve capitalization of the source.  There was also feedback that the nonnormalized transcription exceptions throughout the PS were structurally confusing.  As PS editor at the time, I made the editorial decision to continue the DCRM alternative for recording original punctuation--seperate from recording capitalization from the source--and to refer catalogers/agencies that wanted to preserve both punctation and capitalization to the RDA basic transcription guidelines versus reproducing all the instructions for the nonnormalized transcription option within the PS.   I will admit, this decision was made before the basic transcription guidelines were "finalized" in the RDA BetaToolkit, and there are couple things that are not ideal about RDA basic transcriptions guidelines from a rare materials perspective.  For the MVP, I still think that referring to RDA basic transcriptions guidelines is the most straightforward path for providing an option to preserve both capitalization and punctuation at this point in the editorial process.  

So the broader editiorial question, does editorial team affirm having the following transcriptions options within DCRMR?
-Normalized transcription of capitalization and punctuations.  (Default approach in current draft)
-Normalized transcription of capitalization, retaining original punctuation.
-Nonnormalized (i.e. "take what you see") transcription, retaining both original punctuation and capitalization and following the RDA basic transcription guidelines.

As to the question about making a note about type of transcription employed...I remember talking about it during the PS writing (and the idea also came up at the end of 2019 when BSC discused the MAC discussion paper [2020-DP06 Defining a New Field for Manifestation Statements in the MARC 21 Bibliographic Format](https://www.loc.gov/marc/mac/2020/2020-dp06.html). While I do not remember the exact resolution to that discussion, instructions to make a note about the type of transcription used did not make it into the PS draft.  I am open to the idea.  I just wish there was another way to make this designation that is a not free text note.

**Comment by elizhobart** [comment]
Thanks, Deborah and Michelle. In response to Michelle's questions, I support having all of those options available in DCRMR, though suspect the first two (normalized transcription of capitalization/punctuation and normalized transcription of capitalization while retaining original punctuation) will be used most often. As I recall from the BSC meeting, when the question was raised, no one present said that they transcribe capitalization as it appears on the item. However, this is the practice at some institutions, so I think it's important to give the option, even if it's seldom implemented.

Recording a transcription standard is part of data provenance in the post-3R Toolkit. However, as yet there isn't guidance (that I can see) as to exactly how to record it. I'm inclined to put a pin in that until we have more guidance from the larger cataloging community.

**Comment by elizhobart** [comment]
Also, I agree that "nonnormalized transcription" is confusing, since it isn't defined anywhere. I'd suggest rewriting this sentence as: "If not normalizing capitalization and punctuation, follow RDA Toolkit: RDA Guidelines on Basic Transcription ..."

**Comment by ladylazarus3** [comment]
HI folks, just to note, the MARC/RDA Working Group wrote a discussion paper on Data Provenance that will be presented at ALA Midwinter (and i'm presenting on the topic during the next BSC meeting).  The discussion paper gives a variety of methods for data provenance and i agree that data provenance will be an important aspect of recording transcription methods for rare materials catalogers.

**Comment by deborahjleslie** [comment]
I think we should get rid of the word 'nonnormalized'.

Default rule: normalize capitalization and punctuation 
Alternative rule 1: normalize capitalization but retain original punctuation
Alternative rule 2: retain original capitalization and punctuation following RDA's guidelines for basic transcription
[It's unfortunate that RDA chose the term 'basic transcription'--'basic' generally implies reduced or simplified]

Always make a note indicating which transcription is used; or, always make a note if employing an alternative transcription style.

**Comment by dcrmr** [comment]
Per discussion at the last editorial group meeting, "nonnormalized" will be removed from the text. See editorial group notes for December 4, 2020 for discussion of this issue: https://docs.google.com/document/d/1_XLUHBLpDjGSaM6U_3xcYOlyk_vbXUHD/edit.
