### ISSUE TITLE
Questions for BSC review

### ISSUE THREAD

**Issue by elizhobart** [rbms-bsc/DCRMR#135]
Let's use this GitHub issue to gather any questions we'd like BSC reviewers to consider.

**Comment by elizhobart** [comment]
(From Deborah in January 29 BSC meeting)

In the examples, are the serif and sans-serif fonts distinct enough to distinguish labels from example text?

**Comment by deborahjleslie** [comment]
I _really_ like the fonts and hope the reviewers do, too. I'm thinking more along the lines of visual distinction aside from fonts. But perhaps we've beaten this horse to death in our conversations about the the difficulty of introducing different formats when talking about [formatting of examples](https://github.com/rbms-bsc/DCRMR/issues/49) #49

**Comment by mjmascaro** [comment]
Is repeating instructions in the element proper and parallel elements on which statements to record where helpful or a distraction? (For example: 5.21.39 under Place of publication is near identical to 5.215.31.5 under Parallel place of publication.)
