### ISSUE TITLE
Major changes from DCRM(B)

### ISSUE THREAD

**Issue by elizhobart** [rbms-bsc/DCRMR#137]
As we begin to look forward to public review, I want to compile a list of major changes from DCRM(B) along with reasons for the changes. In many cases, these were decisions made by prior editorial groups, which we've decided to retain. As group membership changes, I want to make sure we have the reasons documented. Major changes that I've identified include:

- Punctuation in Roman numerals (0.4.34.1):
- Transcription of vv as w (0.4.74.2)
- Persons or bodies not explicitly named as other title information, not statement of responsibility (1.23.34.1)
- **Note: in post-BSC review edits, instructions for 6.21.421.2 were reversed, reverting to DCRM(B) instructions. This is no longer different.** 6.21.421.2: instruction to make a note if text is printed on both sides of a leaf but are numbered on only one side. DCRM(B) instructed catalogers to make a note when leaves were numbered and printed on one side only.

Please use this issue to flag any other major changes I may have missed and to discuss reasoning for the changes.

**Comment by elizhobart** [comment]
Persons or bodies not explicitly named (1.23.34.1) was discussed in GitHub issue #98. The reason for this change is that in the new Toolkit, if no agent is referenced, the statement cannot be recorded as a statement of responsibility. The new Toolkit defines "statement of responsibility" as: "A statement that identifies, and indicates the function of, an agent who is responsible for a work or its expression that is embodied by a manifestation. A statement of responsibility may include words or phrases that are neither names nor linking words." Therefore, a phrase such as "translated into English" is not a statement of responsibility. "Translated by a teacher," on the other hand, is a statement of responsibility, as the agent ("a teacher") is referenced, even if not by name.

**Comment by elizhobart** [comment]
Punctuation in Roman numerals (0.4.34.1) was discussed in issue #107 and based on a meeting at the Walpole. The decision to retain punctuation on the principle of "take what you see." In particular, the concept of "word integral" punctuation (versus punctuation at the end of the word) was raised, with a general decision to retain punctuation that is word integral.

**Comment by deborahjleslie** [comment]
### Transcription of vv as w (0.4.74.2)
Background: during the final stages of editing DCRM(B), we were alerted to a a new-to-us character approximation used in German blackletter: round r + v for w. The editorial team realized we needed to grapple with this, and indeed already had other  cases of character approximation--l2 for 'k' and if course vv for 'w'. 

The principle agreed on is that if typographic characters are used to _approximate_ another character, we transcribe as the intended character. Therefore, 'l2' is 'k' and 'rv' is 'w'. Had we the courage of our convictions, we would have also required the transcription of vv as 'w'. As I said, however, we were at the end of a very long process and in a very human way decided to leave vv as 'vv' for the time being, always with the intention that the next iteration would pull 'vv' as approximated 'w' into line. The DCRM2 PS group concurred.

**Comment by elizhobart** [comment]
We've made addition of repository identifier a required part of local notes ("always" instead of "if considered important" in DCRM(B)).
