### ISSUE TITLE
Physical characteristics usually omited from description of printed books

### ISSUE THREAD

**Issue by lizoknj** [rbms-bsc/DCRMR#14]
(Discussed during the text finalization phone call on June 2)
Some physical characteristics of printed books are usually omitted from descriptions, because they are all but universal.

Examples:
    Production method: Printing
    Base material:  Paper
    Applied material: Ink

These types of physical characteristic have usually been mentioned only if the resource differs from the norm, e.g. it has an engraved title, or is printed on vellum or some other material other than paper.

During yesterday’s phone call, I asked whether DCRMR should give guidance for or against including this information in descriptions, or whether it was better to treat these as options, “if considered important”, like all the other types of production methods and materials. 

The consensus was in favor of making these terms optional. I will reword the instruction in production method so that it applies to the manifestation as a whole, not just to the illustrations.

**Comment by mjmascaro** [comment]
@lizoknj will draft some language for group review.
