### ISSUE TITLE
Appendix F (Title Access Points)

### ISSUE THREAD

**Issue by elizhobart** [rbms-bsc/DCRMR#16]
Information recorded in DCRM(B) appendix F maps to RDA elements, chiefly Varying Title of Manifestation, but also Preferred Title of Expression and Title of Item. I would like to incorporate these into the main body of the text, but I'm concerned about adding additional work to the text finalizing group at this juncture. Should we plan to revisit later, or add these to the text now?

**Comment by ladylazarus3** [comment]
In the interest of numbering and the website development work, i would prefer this chapter to be incorporated sooner than later.

**Comment by flapka** [comment]
@elizhobart @deborahjleslie 

FWIW, I think our pre-3R drafts of RBMS PS have already incorporated the guidance from Appendix F into variant title. See: https://docs.google.com/document/d/1xINV0NUOlhHWzQfIyuPrb1vUjbr2PXDAnq6M96z_zHw/edit

**Comment by mjmascaro** [comment]
At June 17, 2020 Editorial Group Meeting, decided to incorporate appendix F in the main body of text.  Leaving this issue temporarily open as reminder of work assignment needing to be made.  See [meeting notes ](https://docs.google.com/document/d/11a55GuLkWWEFBg8MiQPBnuQI_pw989Tbne8nX0zNmgo/edit?usp=sharing)for more details.

**Comment by mjmascaro** [comment]
Adding comments that kalan previous made on old [General Discussion document](https://docs.google.com/document/d/13SVLzOAV71pom_jWNX67Tc-4iqwrbhLqgdvim8NaZNc/edit?usp=sharing).

kalan  Just FYI to Elizabeth and Michelle who have been working on the various note sections.  I have created a Google doc for Manifestations: variant title of manifestation, but the instructions for variant titles are festooned all around DCRMB prime.  Here is a copy of the relevant instructions from the index for title access points and Variant titles:

- Title access points: Appendix F
- for variant forms of title: Appendix B4 (246), Appendix C3 (246)
- variant: 7B4, 7B5, Appendix B4 (246), Appendix C3 (246), Appendix F2 (7B4‐7B5)

I know that you folks were working on various appendices and note sections and didn’t want to cross wires or duplicate efforts.  I do feel like the various instructions for variant titles should be arranged under the Variant title of manifestation element. There is a [google doc here](https://docs.google.com/document/d/162Fj-kZdxhBXJ-grtyQKPHlXyBj7fJeUpYTyY22Itcs/edit#heading=h.rkgo3gie23qj).

**Comment by elizhobart** [comment]
Per email discussion with the title group, we will be incorporating instructions in Variant title of manifestation and Title of item in the initial release of DCRMR. Instructions mapping to Preferred title of expression will be held for the time being and will be added to GitHub issue #36 (Future work).
