### ISSUE TITLE
New charts for early letterforms and brevigraphs

### ISSUE THREAD

**Issue by rbms-bsc** [rbms-bsc/DCRMR#162]
Eventually, we're going to need to re-do our charts for Early letterforms and Brevigraphs -- they're beginning to lose sharpness in the on-line environment/display.

We might want to consider using embedded images (ex. [ye](https://rbms-bsc.github.io/DCRMR/assets/pictures/transcription/ye.png) and formatting it as a table. However, that's a future discussion.

**Note:** This issue was originally posted by @rarebkcat on 19 August 2020 as a [comment](https://github.com/rbms-bsc/DCRMR/issues/36#issuecomment-676498543) on issue #36, which was created as a catch-all for issues related to future development. For ease of tracking, the comments have been moved to their own individual issues and tagged as "future work."

**Comment by rbms-bsc** [comment]
I just ran across a CD with the original images. I can send that to the editors if that might help.

**Note:** This comment was originally posted by @deborahjleslie on 19 September 2020 as a [comment](https://github.com/rbms-bsc/DCRMR/issues/36#issuecomment-695341499) on issue #36, which was created as a catch-all for issues related to future development. For ease of tracking, the comments have been moved to their own individual issues and tagged as "future work."

**Comment by rbms-bsc** [comment]
Hi, Deborah -- That would be useful!

I can email you my mailing address, if that works? Unless you wanted to pull them off and upload them yourself?

-Amy

**Note:** This comment was originally posted by @rarebkcat on 20 September 2020 as a [comment](https://github.com/rbms-bsc/DCRMR/issues/36#issuecomment-695793951) on issue #36, which was created as a catch-all for issues related to future development. For ease of tracking, the comments have been moved to their own individual issues and tagged as "future work."

**Comment by rbms-bsc** [comment]
Review instruction 0.4.16.3 on transcription of Tironian sign. Continue to transcribe it as an ampersand or change to "[et]"? See [DCRM-L thread from September 2021](https://listserver.lib.byu.edu/pipermail/dcrm-l/2021-September/006481.html) for more context and arguments in favor or revising the instruction.

**Note:** This comment was originally posted by @jess-grz on 21 September 2021 as a [comment](https://github.com/rbms-bsc/DCRMR/issues/36#issuecomment-924072406) on issue #36, which was created as a catch-all for issues related to future development. For ease of tracking, the comments have been moved to their own individual issues and tagged as "future work."

**Comment by deborahjleslie** [comment]
This can be closed; a new brevigraphs table with completely new images and links has been prepared by Erin Blake, and the Brevigraphs working group--which took a hiatus from their work of proposing new principles--is now also working with the Keepers on maintenance and display.

**Comment by rbms-bsc** [comment]
Thank you @deborahjleslie!
