### ISSUE TITLE
DCRMR editorial guidelines

### ISSUE THREAD

**Issue by deborahjleslie** [rbms-bsc/DCRMR#18]
Opening this issue now to provide a link to the DCRM editorial guidelines. 
http://dcrmedits.pbworks.com/w/page/69461273/DCRM%20Editorial%20Guidelines%20and%20Errata

**Comment by deborahjleslie** [comment]
I assume you want to keep the development of labels close for consistency. What do you think about a label indicating that this isn't current information?

**Comment by ladylazarus3** [comment]
Thanks for the link to the DCRM editorial guidelines, Deborah! :)  i've started to create some pages in the Github repository's wiki space to create [templates](https://github.com/rbms-bsc/DCRMR/wiki/Template:-Entity-Template-for-DCRMR) similar to the use of a master Word document for the published DCRM manuals and ["how to" guides](https://github.com/rbms-bsc/DCRMR/wiki/How-to-populate-a-new-Entity-Markdown-file) for creating and maintaining web-pages on the Github site.

i know there is still a lot of tweaking to do, but does this look like a good start?  i know we are building the tracks under the train as we go, but if folks have some wiki-related pages that should have priority (esp. how-tos or further templates that are needed), please don't hesitate to let us know.

With thanks and blessings,
kalan

**Comment by ladylazarus3** [comment]
Just an update on the [DCRMR editorial wiki space], we have instructions/templates for
- [entity pages](https://github.com/rbms-bsc/DCRMR/wiki/How-to-populate-a-new-Entity-Markdown-file)
- [chapter pages](https://github.com/rbms-bsc/DCRMR/wiki/Template:-Chapter-Template-for-DCRMR)
- [glossary pages](https://github.com/rbms-bsc/DCRMR/wiki/How-to-populate-a-new-Glossary-Page)
- [prelim pages](https://github.com/rbms-bsc/DCRMR/wiki/How-to-populate-a-new-Prelims-Page)

Are there other master templates that we might need?  i could make instructions/templates for a potential future index (understandably an index might not be part of the Minimal Viable Product, but the website's built in "search feature" might not be a worthy replacement for an index), but it would be good for me to think through the "how to make an index in GitHub" sooner than later so there are no yucky surprises down the road.

If we do decide we need an index, the [xref spreadsheet between DCRM(B) to DCRMR instructions](https://docs.google.com/spreadsheets/d/1nP4uJPxj6gbfWPcPusKxAqxBXbQW9HG8uoU1SxZMqq0/edit#gid=2022670504) will be invaluable, not just for us, but for folks working on future format modules as well.

**Comment by elizhobart** [comment]
@ladylazarus3 @rarebkcat could we put this link somewhere in the wiki? I was thinking of maybe creating a "historic documentation" page or something similar but wanted to check with you first, since you both have the best sense of what we already have in the wiki.

**Comment by ladylazarus3** [comment]
Absolutely!  i added the link to [this page](https://github.com/rbms-bsc/DCRMR/wiki/DCRM-Editorial-Guidelines-and-Errata), does that work for you both @deborahjleslie and @rarebkcat?  Right now we have enough content to warrant a [DCRMR Wiki Contents page](https://github.com/rbms-bsc/DCRMR/wiki), but it really has been a 'build it and revise it as we go' type of thing.  So we are very happy to add or remove resources or entire pages for folks as needed.  

kalan

**Comment by elizhobart** [comment]
Great! Thanks, kalan. This works for me and should make it easier to find in the long run instead of keeping it in issues. If this placement looks good to @deborahjleslie and @rarebkcat, I'll close this issue.

**Comment by deborahjleslie** [comment]
Thumbs up
