### ISSUE TITLE
Readme for GitHub's front page?

### ISSUE THREAD

**Issue by ladylazarus3** [rbms-bsc/DCRMR#19]
Hi folks,  
i know we've talked about this in our editorial meetings, but thought i should formalize with an issue.  i'd like for us to add a readme file to the GitHub repo.  This readme just tells folks about our site and the scope of our work.  i think much of the language can incorporate aspects of the introductory prelims materials (history of the standard, publishing plans, and the who/what/when/where/why-ness of the site) with an emphasis on GitHub's role and our decisions for hosting here.  i know this isn't a high priority right now, but it might be a nice last "polishing step" before launch.  To my knowledge, we don't have a GoogleDoc with this information-- and to my mind-- would want lots of eyes on before we added the readme to the repo.  GitHub just "helpfully" reminds me this hasn't been done yet every time i log in, so i  thought i'd make a note of it here.  Thanks and with kindest regards,

kalan

**Comment by lizoknj** [comment]
Since this site isn't open to the public yet, could you just create a readme file that said very little (maybe, "Stop nagging me!"). That would shut up the GitHub police, and then we could work on something more substantial before the site goes live.

**Comment by mjmascaro** [comment]
I think a short readme file identifying what the project is and the body commissioning it, BSC, would not hurt.  At this point I do not think it needs to elaborate as much as the preliminary.  Probably steal some language from here: http://rbms.info/dcrm/rda/ and call it a day.

**Comment by ladylazarus3** [comment]
Excellent!  Thanks, i added a readme to the repository. 
kalan

**Comment by dcrmr** [comment]
[Readme.md](https://github.com/rbms-bsc/DCRMR/blob/master/README.md) added to the repository and will be updated in the future as needed.
