### ISSUE TITLE
Write up succession documentation on reindexing the Algolia search functionality

### ISSUE THREAD

**Issue by dcrmr** [rbms-bsc/DCRMR#2]
The DCRMR website uses Algolia to populate the search feature embeded within the site.  Although the search feature is setup successfully, it will have to be reindexed occasionally using commands in GitBash.  To close this issue:
1.  We need to write up documentation on reindexing the Algolia search functionality
2. We need to publish this documentation as a markdown file within the Appendices of the DCRMR itself
3. Create a holistic "maintenance cycle" documentation that includes updating the index periodically (quarterly?)

**Comment by ladylazarus3** [comment]
i have drafted the succession documentation for reindexing the Algolia search app.  The instructions are available as a sub-page within the DCRMR Editorial Guidelines Wiki:
https://github.com/rbms-bsc/DCRMR/wiki/Reindexing-the-Algolia-search-feature

Does it need anything else?  It should be pretty straightforward once folks have the Algolia account credentials and Git Bash set up on their local machine.

**Comment by dcrmr** [comment]
Documentation [How to reindex the Algolia search feature](https://github.com/rbms-bsc/DCRMR/wiki/How-to-reindex-the-Algolia-search-feature) has been added to the [DCRMR Editorial Wiki](https://github.com/rbms-bsc/DCRMR/wiki).
