### ISSUE TITLE
Chief Title [from Gdoc]

### ISSUE THREAD

**Issue by mjmascaro** [rbms-bsc/DCRMR#22]
@ladylazarus3 original post:
Should “chief title” remain being called “chief title”  in RDA so many things have changed from “chief” to “preferred ... “  Can we change it to “preferred title” and have a cross reference in the glossary, or is this cheating/a bad idea/confusing/etc.  I’m just worried that future catalogers that don’t remember “chief source of information” won’t be able to understand the significance of “chief” anything and won’t make the right associations.

[MM: To get the conversation started…
I would like to avoid “preferred title” since it had a different connotation in Pre 3R toolkit.
In PS drafts, we got around [i.e., avoided]  the whole chief title issue by providing an alternative scope for title proper that matched the DCRM definition of title proper (see https://docs.google.com/document/d/184B1KN9BbB51uXpFS5DEo7dIaZ2yC4lDC419ZtIdFwM/edit#bookmark=id.kp1dedfy3dxc ) Is that a viable solution?]

Note: Issued raised at [Feb. 18, 2020 Editorial Group Call.](https://docs.google.com/document/d/13JuQMwC903-mo2D9MrLA_RS-7Jp4m_dfdFX8EBuww3k/edit?usp=sharing).  Limited discussion, were going to pick up in different format and then the pandemic happened.

**Comment by deborahjleslie** [comment]
"Chief title" doesn't mean what you think it means. It is the basis of identifying the title proper, but is neither synonymous with "title proper" nor is it directly referring to "chief source of information." It's an important, if hard-to-understand concept crucial in cataloging rare materials, where titles often start with introductory verbiage.  

From the glossary:
**Chief title**. The distinguishing word or sequence of words that names a publication, as given on the title page (or substitute). This definition excludes alternative titles, parallel titles, other title information, and subsidiary title information preceding the chief title on the title page, such exclusion resulting usually in a short title. See also Title proper.

**Comment by mjmascaro** [comment]
I am okay with incorporating the "chief title" as part of the instructions for title proper.  I think some of the confusion arose due to the pre 3R Toolkit defining title proper as "chief name of a manifestation" which is a similar to "chief title." The PS drafts expanded the definition of title proper to include introductory words.  (The post 3R Toolkit definition of "A nomen that is a title of manifestation that is selected for preference in a specific application or context" is a little more opaque.)

Since the glossary may not be finished as part of the initial release of DCRMR, I think it would be helpful to incorporate the definition of chief title into the rule text.

My preference would be to not create a new element for chief title (mainly since we already have so many elements and even in our environment chief title does not have its own MARC tag).

**Comment by deborahjleslie** [comment]
"Chief title" doesn't mean what you think it means. It is the basis of identifying the title proper, but is neither synonymous with "title proper" nor is it directly referring to "chief source of information." It's an important, if hard-to-understand concept crucial in cataloging rare materials, where titles often start with introductory verbiage.  

From the glossary:
**Chief title**. The distinguishing word or sequence of words that names a publication, as given on the title page (or substitute). This definition excludes alternative titles, parallel titles, other title information, and subsidiary title information preceding the chief title on the title page, such exclusion resulting usually in a short title. See also Title proper.

**Comment by deborahjleslie** [comment]
Agree. Really glad they dropped that "chief name of a manifestation" from the Toolkit!

**Comment by ladylazarus3** [comment]
hi folks,  thanks for the discussion.  i think this was from a time when i was trying to figure out how to wrangle 'chief title' into its spot in RDA, i can see (again) i got myself wrapped up in words.  i agree that the instructions should remain where they are in title proper.

As a mock up, here is an example of what a [glossary page](https://rbms-bsc.github.io/DCRMR/general/glossary/C/) currently looks like using [chief title](https://rbms-bsc.github.io/DCRMR/general/glossary/C/#chief-title) and [title proper](https://rbms-bsc.github.io/DCRMR/general/glossary/T/#title-proper) as experimental examples.
