### ISSUE TITLE
Note on statement of responsibility when there is no statement

### ISSUE THREAD

**Issue by deborahjleslie** [rbms-bsc/DCRMR#24]
Related to https://github.com/rbms-bsc/DCRMR/issues/20 

Instructions in DCRM, while mostly confined to the manifestation, include notes and other elements that relate to the work or expression. Now that we've decided to incorporate instructions and examples for notes with the relevant chapter and not have a Notes chapter (if I understand the intention correctly).    

The _Manifestation: Statement of responsibility_ chapter has three elements: _Statement of responsibility_; _Parallel statement of responsibility relating to title proper_; and _Note on Statement of responsibility_ 

**Example**: The resource in hand is published anonymously, but the author is known. We naturally want to make a note about it. A work's creator is a work-level entity, but there is no work element [Note on agent](https://beta.rdatoolkit.org/en-US_ala-77406bec-78f8-376e-978b-b6f56e535346) (that's an agent entity and properly belongs in an authority record--I think). This leaves us with a dilemma--do we use the higher-level element but amorphous [Note on work](https://beta.rdatoolkit.org/en-US_ala-521fa629-f515-3247-9db0-f03e8736bf15), which fits the RDA definition of the element, or use the incorrect [Note on statement of responsibility](https://beta.rdatoolkit.org/en-US_ala-ec50e693-78cd-3171-8f30-0d5be6e8a634), which by definition pertains to a statement embodied on the manifestation. Which we don't have, because this manifestation has no statement. 

The problem is not unique to dcrmr--DCRM and predecessor standards placed instructions for attributions in the [Statement of responsibility](https://beta.rdatoolkit.org/en-US_ala-a39c4ac1-03cb-351b-8868-f64d7dd16de4) element. This uneasy fit is, however, thrown into sharp relief when trying to associate dcrmr elements with their precisely-defined RDA elements. 

Is there a better way? Given that we're going for a minimum viable product, maybe not. What are the consequences of kicking this ball on down the road instead of confronting it now?  

UPDATE: after composing this, I discovered that Note on agent maps to MARC bibliographic 500 and 545, which means that it **can** be used in bib records. What does this mean for DCRMR and our current element list?

**Comment by flapka** [comment]
For the example described, I assume the true RDA mapping is to [Work: creator agent of work](https://beta.rdatoolkit.org/en-US_ala-6277a869-961d-379f-8ae8-7ec159052a26). 

If we record such information with an access point, IRI, or structured description, we can use a 1xx field in MARC. 

If we want to express such information as free text (e.g. "The book was written by my cat."--Lapka) -- an unstructured description -- we can put in a 500 field in MARC. 

And of course we can use these in combination. This aligns with the MARC mapping that RDA gives for the element.

**Comment by deborahjleslie** [comment]
The example is strictly about mapping the note, not about mapping to the creator element. There's no problem with how to encode a note about authorship in MARC, but rather how to incorporate it into the framework of individual elements. I'm objecting to mapping a note about the agent to a note about the statement of responsibility. 

I don't remember--were we planning on doing away with ISBD area 7 entirely?

**Comment by lizoknj** [comment]
It's cheering that there is someplace to park it on the bib record. I think it would have to be the 500 note rather than the 545, which is for biographic information or administrative history of the main entry. I wonder how many RDA notes (and RDA elements) will end up coded as 500's?

**Comment by elizhobart** [comment]
We are not eliminating ISBD area 7 entirely. There will be chapters for general notes (i.e., manifestation-level or higher) and item notes. I agree with your point, Deborah, but I think this could be recorded as note on statement of responsibility within RDA, as this scenario is addressed under "note on statement of responsibility" in both RDA 1.0 and the Beta Toolkit. Let's plan to discuss with the whole group at the next meeting.

**Comment by elizhobart** [comment]
Decision from July 13 editorial group meeting: record this as a note on statement of responsibility. This is permitted by RDA and likely where catalogers will look for this instruction.

**Comment by deborahjleslie** [comment]
I concur. Notes on attributions in the absence of statements of responsibility can be considered a Note on statement of responsibility, namely, that there isn't one!

**Comment by deborahjleslie** [comment]
I believe this issue can be closed now.

**Comment by flapka** [comment]
Me too. Putting this info in Note on SOR seems the most elegant and sensible solution.

**Comment by dcrmr** [comment]
Discussed in [2020-07-13 DCRM-RDA Editorial Group meeting](https://docs.google.com/document/d/1NkRDh3Pfr0qV4mDISqyQ_IZ2_ePzpHA46V9JdZAOgoc/edit).  Group consensus to record as a note on statement of responsibility.
