### ISSUE TITLE
Guidance on formal / informal notes (needed?)

### ISSUE THREAD

**Issue by flapka** [rbms-bsc/DCRMR#27]
Our draft for [Manifestation: note on manifestation](https://docs.google.com/document/d/1-3VSYESps0x8vAIuR-OpFAueCieRnuSZDGWzlHR12L4/edit#) includes guidance that refers to"formal" and "informal" notes, carried over whole from DCRM(B). We omitted this guidance in the PS drafts, but it reappears here. 

Do we need this guidance? I could go either way, but if kept it seems we'd want clearer description of the distinction, with examples.

**Comment by ladylazarus3** [comment]
i think it might be good to keep.  Some thoughts on where this could go (organizationally speaking) in DCRMR either:

- add a section talking about "formal" and "informal" notes on the [Examples and notes](https://rbms-bsc.github.io/DCRMR/books/introduction/Examples-and-notes/) preliminary page
- add "formal" and "informal" notes to chapter-level pages regarding notes, such as [Chapter 7. Other notes](https://rbms-bsc.github.io/DCRMR/other-notes/) and [Chapter 8. Notes on items](https://rbms-bsc.github.io/DCRMR/notes-on-items/) chapters.
- we could add definitions for "informal" and "formal" notes to the [Glossary pages](https://rbms-bsc.github.io/DCRMR/general/glossary/C/).  They aren't included in the DCRM(B) glossary or the glossary of my 1988 AACR2 copy.  so there really isn't a precedent for it, but i mean, hey, glossaries are glossaries.

Certainly, i think making sleek notes that are clear and follow a precedent can be a time-consuming task in rare materials cataloging.  Personally, i think we should keep the guidance and add more examples.  i have an entire GoogleDoc of examples that i've scoured WorldCat for over the years-- sometimes you just find a really well done note and think "ah ha!" i should put this in my pocket for later.

**Comment by elizhobart** [comment]
I suspect that this instruction re-appeared due to basing the new text more on DCRM(B). I likewise don't have strong feelings on this, but tend to prefer to follow the precedent of the RBMS PS draft. A quick search also suggests the distinction between formal and informal notes doesn't appear anywhere else in DCRMR. My inclination would be to remove it, but maybe this would be a good issue to raise with the group at our next meeting.

**Comment by mjmascaro** [comment]
Like Elizabeth, I also do not have a strong opinion, but do lean towards removal since the distinction does not appear elsewhere.

**Comment by elizhobart** [comment]
Decision in July 29 meeting to omit instructions on formal/informal notes.
