### ISSUE TITLE
Future work

### ISSUE THREAD

**Issue by elizhobart** [rbms-bsc/DCRMR#36]
A few folks have highlighted some specific areas that will need to be revisited during the editorial group review. This ticket will serve as a parking lot for those issues. If you encounter anything that doesn't need immediately resolution but you'd like the group to watch for during our review, please put them here.

**Comment by mjmascaro** [comment]
There seems to be some inconsistency on when instructions on making a note on transposition are included with specific cataloging instructions or whether there is an instruction at the beginning of the element to cover them all. (See [Example](https://docs.google.com/document/d/1RdsSOlT6xC6qTydK7dJvNiZUxUFYXDeUPFbe3a_u-zQ/edit#bookmark=id.zcf5h874e8fw). This something that would be good to watch out for and look at holistically during full text review.

**Comment by elizhobart** [comment]
In discussion of color content (#33 ), we felt that including instructions on MARC coding were valuable, specifically recording an unstructured description in 300 $b and an optional structured description in 340 $g. However, this can't be included in the main DCRMR text, as DCRMR is metadata standard-neutral. Flagging this to add to a future application profile or similar tool.

**Comment by mjmascaro** [comment]
Similar to above comment, in discussion of edition statements that do not apply to the whole manifestation (#32),in DCRMR had MARC example for how to use 250 $3 to indicate which particular volume of a multipart monograph a particular edition statement appeared on.  Example revised to more coding agnostic, but specific encoding example maybe included in another tool?

**Comment by mjmascaro** [comment]
DCRM(B) 2C4 (Statements of responsibility related to edition in more than one language or script) included instructions related to ISBD order that did not get carried over into DCRMR main text, since trying to be more ISBD agnostic. Perhaps, this can be included in another tool.

**Comment by mjmascaro** [comment]
Precataloging decisions (DCRM(B) X) is one of the preliminaries that is slated to be completed after the initial round of DCRMR.  There are two alternative rules in Designation of edition related to creating descriptions for individual impressions, state, etc. that in the DCRM(B) rule they were based on had a reference to X.1.4 from the preliminary section that will need to be crossed back when that section is written.

**Comment by jess-grz** [comment]
Portions of DCRM(B) [Appendix F](https://docs.google.com/document/d/1EnvmqKnAkduL6MC7JUvdk5kImER3kMIXJkf1COdY6Gw/edit) (Title access points) cover Preferred title of expression (1F1-1F2, first half of 1G1-1G8, and 7B11). We will address at a later time. (See [#16](https://github.com/rbms-bsc/DCRMR/issues/16))

**Comment by rarebkcat** [comment]
Eventually, we're going to need to re-do our charts for Early letterforms and Brevigraphs -- they're beginning to lose sharpness in the on-line environment/display. 

We might want to consider using embedded images (ex. [y<sup>e</sup>](https://rbms-bsc.github.io/DCRMR/assets/pictures/transcription/ye.png "ye") and formatting it as a table. However, that's a future discussion.

**Comment by deborahjleslie** [comment]
### Manifestations without titles
I would like the group eventually to consider whether to expand and encourage the use of devised titles proper when the manifestation in hand doesn't have a recognizable title. By _recognizable title_ I mean A word or sequence of words appearing in the manifestation that is clearly intended to name it. Single-sheet publications, including poems, songs, proclamations and such are the main suspects, but there are also manifestations such as that addressed by dcrmb 1B3.3, Title proper consisting solely of the name of a responsible body. 

1B5, No title [previously _No title proper_] gives instructions on what to transcribe when you don't have a title, which is generally to use the opening lines of text. This is okay with poems, and possibly with proclamations, but not for a lot of other things. Instructions are expanded in 1G2, on Single-sheet manifestations. Personally, I think we could eliminate a special section on single-sheet publications and integrate the rules into other elements.

**Comment by rarebkcat** [comment]
Currently, in transcription we have a reference to the LC PCC PS 1.7.5, "Symbols." That reference will need to be updated with the next iteration of the LC PCC Policy Statements are published.

**Comment by rarebkcat** [comment]
When editing instructions post-publication, we need to think through versioning and how to (if to) explicitly indicate that an instruction was edited. (Keeper note to self: look at GitHub versioning in practice and think from there.)

**Comment by deborahjleslie** [comment]
Parallel title proper needs a proper rewrite, now that it's been narrowed from Parallel title. 

@jess-grz and @lizoknj  agreed with me on a rewrite of certain instructions to make them clearer, and I've fiddled with examples. In some cases I've intentionally departed from the example protocols in terms of including other elements in hopes of making the examples make sense.

**Comment by deborahjleslie** [comment]
Parallel title proper needs a proper rewrite, now that it's been narrowed from Parallel title. 

@jess-grz and @lizoknj  agreed with me on a rewrite of certain instructions to make them clearer, and I've fiddled with examples. In some cases I've intentionally departed from the example protocols in terms of including other elements in hopes of making the examples make sense.   

> 
> 
> Eventually, we're going to need to re-do our charts for Early letterforms and Brevigraphs -- they're beginning to lose sharpness in the on-line environment/display.
> 
> We might want to consider using embedded images (ex. [ye](https://rbms-bsc.github.io/DCRMR/assets/pictures/transcription/ye.png) and formatting it as a table. However, that's a future discussion.

I just ran across a CD with the original images. I can send that to the editors if that might help.

**Comment by deborahjleslie** [comment]
> 
> 
> Eventually, we're going to need to re-do our charts for Early letterforms and Brevigraphs -- they're beginning to lose sharpness in the on-line environment/display.
> 
> We might want to consider using embedded images (ex. [ye](https://rbms-bsc.github.io/DCRMR/assets/pictures/transcription/ye.png) and formatting it as a table. However, that's a future discussion.

I just ran across a CD with the original images. I can send that to the editors if that might help.

**Comment by deborahjleslie** [comment]
### Substantive rewriting needed for Single-sheet manifestations

Related to https://github.com/rbms-bsc/DCRMR/issues/94. Not sure if integration of instructions for single-sheet manifestations, in DCRM(B) occupying its own section at the end of Area 1, is going to be viable for a minimum viable product; adding it to Future work.

**Comment by deborahjleslie** [comment]
### Addition to Title of item
Add an instruction for optionally adding the title of a blank form that has been completed in manuscript. See [1.26.4.10 Title proper with an interpolated blank](https://docs.google.com/document/d/162Fj-kZdxhBXJ-grtyQKPHlXyBj7fJeUpYTyY22Itcs/edit#)

**Comment by rarebkcat** [comment]
> I just ran across a CD with the original images. I can send that to the editors if that might help.

Hi, Deborah -- That would be useful! 

I can email you my mailing address, if that works? Unless you wanted to pull them off and upload them yourself? 

-Amy

**Comment by rarebkcat** [comment]
Transcription -- Key Designations was removed as being a discrete section of format-specific text. Review and add back in when DCRM(Music) is incorporated.

Text, including coding (Sept. 22, 2020):

```
### 0.5.18 Key designations

<a name="0.5.18.1">0.5.18.1</a> Transcribe accidentals (flat and sharp signs, etc.) directly following the key letters being modified. Do not insert a space. 

>Example:  
><CITE>A&#9837; major</CITE>

<a name="0.5.18.2">0.5.18.2</a> If minor keys are represented by lowercase letters in the chief source, transcribe them as lowercase. Otherwise, record any letter(s) representing the key in uppercase.
```

Text:
Key designations

Transcribe accidentals (flat and sharp signs, etc.) directly following the key letters being modified. Do not insert a space. 

Example: 
A&#9837; major

 If minor keys are represented by lowercase letters in the chief source, transcribe them as lowercase. Otherwise, record any letter(s) representing the key in uppercase.

**Comment by rarebkcat** [comment]
DCMR(C) - Dedications

When working on Transcription, I found that the RBMS PS had some instructions re: dedications at  RBMS PS 2.3.4.1 that are no longer present in DCRMR. (The RBMS PS instructions for transcription had a reference to the instructions at 2.3.4.1.)

Michelle provided the following context: 

> The DCRM Steering Group (body that was reconciling differences between the different DCRM modules) discussed in 2014 some changes to treat dedications due to recommendations brought up by Cartographics. Ultimately, Cartographics was granted a format exception to record grammatically inseparable dedications in a note versus other title information.
> * http://dcrmsteeringgroup.pbworks.com/w/page/75430316/Discussion%20topic%3A%20Dedications 
> * The RBMS PS did include a mock-up of how dedications are treated differently for cartographic and graphics (which had format specific reason to adopt C’s treats.) versus books   https://docs.google.com/document/d/1lsD58Nb0dmVYe_VRqYVunqcby0VsoqZZOoiM-Twonoo/edit#bookmark=id.gkfwock3owi1 
> 
> Since for books dedications on title pages are not silently omitted, they are not called out in DCRMB4 0G5.2. (See DCRM errata http://dcrmedits.pbworks.com/w/page/69463439/Area%200%20errata and DCRMB4 Issues http://dcrmedits.pbworks.com/w/page/135454965/Issues%3A%20DCRMB4) 

When future DCRM manuals are incorporated with DCRMR, the instructions for dedications in the RBMS PS will likely need to be re-visited/re-integrated.

**Comment by deborahjleslie** [comment]
> 
> 
> There seems to be some inconsistency on when instructions on making a note on transposition are included with specific cataloging instructions or whether there is an instruction at the beginning of the element to cover them all. (See [Example](https://docs.google.com/document/d/1RdsSOlT6xC6qTydK7dJvNiZUxUFYXDeUPFbe3a_u-zQ/edit#bookmark=id.zcf5h874e8fw). This something that would be good to watch out for and look at holistically during full text review.

In chapters 1 and 2, we have been keeping instructions about making notes on transposition whenever they are part of the instruction itself. 

I would like to revisit the decision to make notes for the specific element as applied to transposition notes. In Michelle's example, transposition involving an edition statement is a Note on edition statement. Notes on transposition, however, , when in fact the

**Comment by elizhobart** [comment]
Instruction for speech balloons removed from transcription, as it is specifically related to graphics. Make sure this is re-added when Graphics is incorporated.

**Comment by elizhobart** [comment]
3.21.34.1: for internal review, a decision was made to remove this sentence pending further discussion:

> Transcribe edition statements not grammatically linked to another element as individual statements. Indicate the work to which each edition statement corresponds in a Note on edition statement (see 3.26.33.1)

Previously, a suggestion had been made to record this information in successive 250 fields with $3. However, there are a few issues with including this instruction now, including:

- "Grammatically linked" is not defined
- This sentence contradicts the prior instruction
- We have no real-world or in-text examples illustrating this

In the interest of moving forward, I am suggesting deletion from the draft, but would like to continue discussion.

**Comment by elizhobart** [comment]
3.21.37.1: For internal review, we removed an instruction to record information in encoded data or in a note, instructing catalogers instead to just record in a note. The PS draft had made some use of encoded data and MARC examples, but this was the only place in DCRMR that did. To bring into line with the rest of the text, we decided to remove it for now, but want to keep this on the table for the future.

Original sentence: 

> If the manifestation was issued as such, transcribe all edition statements. Indicate the edition statements corresponding to individual volumes through encoded data and/or a Note on edition statement (see 3.26.36.1).

Edited:

> If the manifestation was issued as such, transcribe all edition statements. Indicate the edition statements corresponding to individual volumes in a Note on edition statement (see 3.26.36.1).

**Comment by elizhobart** [comment]
6.355.31.1: when adding Graphics, make sure "Details of mount" is added after "Details of applied material" with link to this element.

**Comment by elizhobart** [comment]
6.23.3 Color content: when additional formats are incorporated (Graphics), it won't make sense to have a general rule focused on illustrations. Leaving as is for now.

**Comment by rarebkcat** [comment]
0.4.92.2 removed, awaiting Graphics.

0.4.92.2 Still images. Consider layout, color, size, and other graphic factors to determine whether text is visually inseparable.
Example:
Portrait of an Irish chief, drawn from life at Wexford
(Comment: Size and location of lettering on material visually indicate that “drawn from life at Wexford” is part of a satiric title and not a Statement of responsibility relating to title proper

**Comment by elizhobart** [comment]
Note: as of February 25, 2021, all graphics-related issues mentioned below have been added to the draft text.

**Comment by elizhobart** [comment]
1.21.372.1 option 2, 1.21.384.1, 1.21.385.1: during BSC review of DCRMR, some objections were raised to the practice of creating separate metadata descriptions for different expressions embodied in a manifestation. These instructions were carried over from DCRM(B) 1F2, 1G7, and 1G8. In the spirit of MVP and in keeping with our practice of not changing instructions from DCRM(B) unless there's an RDA-specific reason or a decision from a prior group, we are leaving these as is for now but want to flag for reconsideration with future edits.

**Comment by elizhobart** [comment]
Language in examples for library copies should be examined and instructions clarified. Currently, some examples have generic phrase "Library's copy" (see 0.4.64.2), while others are more specific (e.g., "Indiana University Library copy," 9.4.34.1). A BSC reviewer commented at 9.41.3.2: "it might be good to put examples related to multiple copy situations. For example, we do "Rubenstein Library copy 2" for second copies. This might be outside the scope of what you're hoping to do." For post-BSC review, we felt this was out of scope, but agreed that it merited a closer look post-review.

**Comment by elizhobart** [comment]
2.21.355.1: some disagreement to this instruction raised in BSC review, with comment: "I think it should be "if considered too numerous."" Since this instruction is carried over from DCRM(B), the revisions group elected to flag for future review rather than incorporate the change at this time.

**Comment by elizhobart** [comment]
When appendix B is added, reinsert this instruction in chapter 1:

1.25.3595 Variant titles of a collection (optional)
1.25.3595.1 Record variant titles by which a collection may be known if they differ substantially from the Title proper and provide useful access points. If most or all of the items in the collection have the same title information and it is considered important, make an added access point for the title.

**Comment by elizhobart** [comment]
1.21.385.1: In response to this sentence: "If there are two or more manifestations printed on a single sheet and each has its own publication, distribution, or manufacture statement, or there is other conclusive evidence that they were intended to be separately issued," a BSC reviewer stated, "I'm not sure that a separate "publication, distribution, or manufacture" is enough to count as conclusive evidence." This instruction was pulled from DCRM(B) 1G8 and will need closer consideration before updating.

**Comment by elizhobart** [comment]
Suggestion from BSC reviewers to add DCRMR elaborations of scope to chapter 1: "I find the RDA definition and scope for titles pretty opaque (when it's really not!). Including a heading for DCRMR Elaboration on scope for Chapter 1 would be really helpful."

**Comment by elizhobart** [comment]
Instructions from 1.21.372 to 1.21.382.2 need a closer look and possible rewrite. See [comments from BSC reviewers on chapter 1](https://docs.google.com/document/d/1szCKBfb1InUPg-VPDDboOIOm1FOoNHP7IpSefsW7gcY/edit). 

Note: a reviewer noted that 1.21.372 is not an option in either the original or post-3R Toolkit. This is an option in the post-3R Toolkit in Title of manifestation, Titles of aggregates section:

CONDITION
A manifestation is an aggregate.
A collective title does not appear in a source of information.
OPTION
Record a value that is a devised title.

**Comment by elizhobart** [comment]
For now, deleting these instructions from Title proper: 

1.21.39 Access points for title proper
1.21.39.1 Title access plays an important role in enabling users to identify and locate special collections materials. Provide access for the entire title proper exactly as transcribed, disregarding initial articles as required by filing rules (see Title of manifestation, 1.2.32).
1.21.39.2 For instructions on providing access points for variants of the title proper, see Variant title of manifestation (1.25.35).

This was creating confusion for reviewers, since this reads as instructions just to record the title proper in the 245. Jessica noted: "This is a holdover from Appendix F. Technically, we transcribe the title proper in the 245 as it appears. But in MARC this is also acting as an access point, and the use of the 2nd indicator allows for the omission of initial articles from indexing. I know that the placement of the instruction looks a bit odd here, since it's no longer in the separate appendix and has lost some of that original context. But I'm not sure where else to put this." Since it was causing confusion, the revisions group decided to remove for now and reconsider if it should be added earlier in chapter 1 later.

**Comment by elizhobart** [comment]
Instructions with "make a note on ..." should be reviewed for consistency. Some instructions use "justify," others "give the basis." These should be more normalized.

**Comment by elizhobart** [comment]
Request from BSC reviewer to reconsider instructions for recording decades and centuries (e.g., 5.23.34.1): Can BSC revisit this, in light of the fact that RDA doesn't treat decades and centuries differently (you just supply the "year" so a "decade" is any ten year period, not the ten year period where the 3rd digit is the same). Rare materials reason for deviation: if you give specific years (e.g., "between 1600 and 1700") when what you mean is "17th century" you lose the implied vagueness of the phrase. Consider instead how Catloging Cultural Objects (CCO) rules separate "Display date" from the machine-readable "Earliest and Latest  Dates". See in particular "Decades and Centuries" on p. 174, which says "Qualify decades or centuries with early, mid-, and late, as warranted. Assign appropriate Earliest and Latest Dates by dividing the decade or century into thirds (for example, late 18th century may be indexed as Earliest: 1770, Latest: 1799),unless this formula is contradicted by available information."

**Comment by elizhobart** [comment]
Need to further investigate phrasing of note, particularly around constructions where we give instructions on information contained in a note (such as "explanatory note" or "to give the basis of"). This phrasing varies.

**Comment by elizhobart** [comment]
Create an appendix for PPDM to provide information on dating systems, roles of publishers/booksellers, etc. In the BSC review, one review suggested adding significant historical information at 5.23.31.5 (see [chapter 5 GDoc](https://docs.google.com/document/d/1z1OZiLXrzM-JdjITLgJPvURgFmflsrcyspFY4HnLr5Y/edit)). The Revisions Subgroup felt this was too much detail for an instruction but agreed on the importance of the information, so we are flagging for future inclusion in an appendix. In addition, some of the detail currently in 5.23.31.5 on Julian/Old Style dates may need to be moved to this appendix, but we are leaving it where it is for now.

**Comment by elizhobart** [comment]
Revisit decisions in PPDM (e.g., 5.21.34.1) to give place of publication of later parts in a note. As Deborah noted in post-BSC review, we are now able to repeat these elements and with "well-formed data," places after the first should be transcribed in their proper element.

**Comment by elizhobart** [comment]
Citation styles: BSC reviewers note that currently format for citations is unclear. The issue isn't fully covered in instructions and examples are inconsistent (for example, "Printed by Thomas Harper for John Parker according to STC"). A reviewer notes: "the citation styles will need to be really clear in the notes. The SCF exists for a reason, and we should further standardize how things are cited in a note when we also include a full citation for a resource."

**Comment by elizhobart** [comment]
Extent of manifestation needs instructions on what to do when leaves of plates are included in pagination. This is currently lacking in DCRM(B), too, so flagging for future work.

**Comment by elizhobart** [comment]
Request from BSC reviewers to add instructions/examples for instances where illustrations are labeled "plates" but are not equal to physical plates, such as when there are [12] physical leaves of plates printed on one side, but illustrations are labelled Plate I-Plate XVII.

**Comment by elizhobart** [comment]
Phrasing is inconsistent in instructions to make a note. As a BSC reviewer commented: "while "Note on extent ..." already specifies note in its name, it seems inconsistent to not use similar language in this section-- something like "record in a note on Details of illustrative content" -- conversely, you could use "note" in both instances with the appropriate "(see Element, Rule number)"  throughout the document."

**Comment by elizhobart** [comment]
We need to add a bibliography and make sure we specify which edition of Gaskell we're citing.

**Comment by elizhobart** [comment]
Reconcile current text with current edition of Chicago. (For example, a recent error was caught with "Ph. D."; Chicago removed the space several editions ago.)

**Comment by elizhobart** [comment]
Notes: need to make a principles distinction for when notes will always be required and not. (For example, notes on transposition and notes on sources of information should likely always be required.) Also need to review all notes elements and make sure they are all flagged as "always" or "if considered important," as appropriate.

**Comment by lizoknj** [comment]
Would notes needed to justify a main or added entry (creator or contributor
name) when the name does not appear in the description constitute another
required category of note?  I just noticed that a note isn't required for
attributions (see 2.29.33 below). I was assuming that the attributed name
was accepted as correct, and would therefore appear as a main or added
entry--but may be misinterpreting. Confused.
2.29.33 Attributions

2.29.33.1 If a statement of responsibility for a person or corporate body
connected with the resource does not appear in the manifestation, and an
attribution is available, give the information in a Nnote on statement of
responsibility if considered important. Include the authority for the
attribution whenever possible.


2.29.33 Attributions

2.29.33.1 If a statement of responsibility for a person or corporate body
connected with the resource does not appear in the manifestation, and an
attribution is available, give the information in a Nnote on statement of
responsibility if considered important. Include the authority for the
attribution whenever possible.

**Comment by deborahjleslie** [comment]
Liz, I would say no. I think it's a good idea to limit required notes to those regarding elements relating to transcription and physical description (in MARCspeak, 245, 26x, 300), but not to elements that elaborate description or provide identification.

**Comment by deborahjleslie** [comment]
You're interpreting the situation correctly, Liz. It was not required in DCRM(B), and probably not in its predecessors (don't have access to DCRB or BDRB). Presumably not required because it's an access point. What you were taught may have reflected standard practice (which it is) or local or LC policy. 

FWIW, not only is this a note that I always make, I also always make a note if a work is anonymous and we don't know who the author is.  

I can give more background if desired on the impetus behind sharply limiting the number of **mandatory** notes in DCRM(B) if desired, but can be boiled down to not overburdening institutions who do not have the resources to do full-on DCRB cataloging and/or those whose administrators were putting pressure on "speeding up" rare materials cataloging in the context of the growing "hidden collections" stormcloud.

**Comment by lizoknj** [comment]
Thanks for the explanation, Deborah. I'm relieved that I wasn't making some
embarrassing mistake about what the instructions meant. I can live with
this instruction not being mandatory, since I imagine most catalogers will
add the note anyway.

Liz

**Comment by elizhobart** [comment]
Consider adding the term "sammelband" to the text. Since publication of DCRM(B), "sammelband" has become more widely used and recognized.

**Comment by elizhobart** [comment]
Question from BSC reviewer at 3.24.32: "Does this need a caveat, and cross-reference to 3.33.32, to point catalogers of hand-press era books to cases where the word "impression" does represent a substantial change? Or do those statements only occur on their own, not as named revisions of an edition?" The revision group did not feel that a change was needed at this time, but agreed to flag as future work, specifically giving considering as to whether statements are on the title page/preferred source of information.

**Comment by jess-grz** [comment]
Review instruction 0.4.16.3 on transcription of Tironian sign. Continue to transcribe it as an ampersand or change to "[et]"? See [DCRM-L thread from September 2021](https://listserver.lib.byu.edu/pipermail/dcrm-l/2021-September/006481.html) for more context and arguments in favor or revising the instruction.

**Comment by rarebkcat** [comment]
From email discussion when implementing BSC review edits in Chapter 6:

**Note on… and Details of… elements**
 
There’s variation in how the General rule is constructed.
 
6.215.421.1: Make a note on details of extent that are not already included in Extent of manifestation if considered important (see 6.21.4245.1).
 
6.225.3.1: Give fuller details of illustrative content if considered important.
 
6.235.3.1: Make a note on details of color content if considered important (see Color content, 6.23).
 
6.245.3.1: Make notes on the dimensions of a manifestation if considered important.
 
6.255.3.1: Record details of base material if considered important (see Base material, 6.25.3.3).
 
6.265.3.1: Record details of applied material if considered important (see Applied material, 6.26.3.5).
 
6.275.3.1: Record fuller details of the production method if considered important (see Production method, e 6.27.3.4).
 
6.285.3.1: Record Details of layout if considered important (see Layout, 6.28.3.2).
 
6.295.3.1: Record Details of bibliographic format if considered important (see Bibliographic format, 6.29.3.3). For instructions on recording Bibliographic format as part of a statement of full collation, see Note on extent of manifestation, 6.215.44.9.
 
6.315.3.1: Record Details of font size if considered important (see Font size, 6.31.3.2).
 
It feels like these should be more consistent. 
 
The instruction – is it:

- Record Details of element if considered important (see Element, x.x.x.x).
- Record details of Element if considered important (see x.x.x.x).
- Record details of information if considered important (see Element, x.x.x.x).

 
The reference link is variously done:

- No link
- (Element name, x.x) -- Links to element page, but not a specific citation
- (Element name, x.x.x.x)

**Comment by elizhobart** [comment]
Add instructions on identifying characteristics of concealed editions (i.e., varying editions that are not identified as such on the manifestation).

**Comment by deborahjleslie** [comment]
> Add instructions on identifying characteristics of concealed editions (i.e., varying editions that are not identified as such on the manifestation).

Different editions that describe differently (e.g., different names in publication statement, different pagination), even if they aren't distinguished by the publisher, aren't concealed editions. Perhaps something like "(i.e., varying editions that are not identified or revealed by basic descriptive elements)."

**Comment by jess-grz** [comment]
> Indicate whether basic or normalized transcription was used and consider making this a required note. This will likely be dependent on recommendations from LC and other groups regarding recording data provenance.

The Editorial Group decided to remove the instruction at 0.4.12.2, "_Optionally_, when converting uppercase to lowercase, add diacritical marks that are not present on the source of information in accordance with the pattern of usage in the text."

Concern regarding this instruction was raised during the DCRMR public hearing on Dec. 8 and in a thread begun on Dec. 9, 2021 on [DCRM-L](https://listserver.lib.byu.edu/pipermail/dcrm-l/2021-December/006567.html). @deborahjleslie noted in response: 

> This option was added during early stages of the of what we were then calling DCRM2, on analogy with ijuv. If memory serves, it was along the lines of "well, if we do this with IJUV, shouldn't we do it with diacritics too?" Conceptual rather than practical or experiential grounds. Bob makes a really good case for removing the option.
> 
> The method of transcription is really significant in how far it is used to identify variants and the like, and is even more significant with original vs normalized punctuation. I would like to see it become a required note in every record identifying it. It may seem tedious, but DCRM(G) requires that every record identify the source of the title, and serials cataloging gives a "Description based on" note. If we were to go this route, this community could come up with normative wording that is brief but descriptive enough to alert catalog users to the parameters of transcription.

The previous issue posted on Oct. 13 (referenced at the beginning of this comment) also addresses similar issues surrounding transcription and data provenance. When we revisit these issues and how to address them in DCRMR, we can consider whether to re-insert 0.4.12.2.
