### ISSUE TITLE
Shorten abbreviation for "physical description" chapter name for use in YAML headers?

### ISSUE THREAD

**Issue by ladylazarus3** [rbms-bsc/DCRMR#46]
Hi folks,

This will take a little bit of Github reworking for multiple files, so i wanted group input before "just going for it".  i'm adding a handy reference column in the [order of the text spreadsheet](https://docs.google.com/spreadsheets/d/1nP4uJPxj6gbfWPcPusKxAqxBXbQW9HG8uoU1SxZMqq0/edit#gid=0)  so folks have a ready-reference for the chapter name as it has to appear in the YAML header of the Markdown files in GitHub in order for the file to successfully "announce its place in the family of things" (to paraphrase poet Mary Oliver).  

["Physical-description"](https://rbms-bsc.github.io/DCRMR/physical-description/) is ridiculously long and will have to be typed ad nauseam to create links between instructions.  Are folks okay with  using "phys-desc" instead of "physical-description"?  i don't think this needs a long or tortured debate (i was hoping for a quick yes/no), but i think if we are going to change it... now is the time we should do it and we will thank ourselves graciously later.

Sound ok with folks?  Other suggestions on shortening it?  Again, this is just for shortening the URLs, the label of the chapter will remain "Physical description" regardless.

kalan

**Comment by lizoknj** [comment]
I'm fine with it

**Comment by elizhobart** [comment]
This sounds good to me.

**Comment by ladylazarus3** [comment]
oh whew!  Sounds great, thanks for the input.  :)  i know we will save our fingers quite a bit of typing. 

And since there are so many chapter names that are a bit different in the permalinks of the Markdown YAML headers, i've added a column to the [order of the text spreadsheet](https://docs.google.com/spreadsheets/d/1nP4uJPxj6gbfWPcPusKxAqxBXbQW9HG8uoU1SxZMqq0/edit#gid=0) with the URL version of the chapter names have to look like.
