### ISSUE TITLE
Typo in transcription

### ISSUE THREAD

**Issue by rbms-bsc** [rbms-bsc/DCRMR#5]
There's a typo in the Transcription file: _pages/General-Rules/Transcription.md

"a typoe a typoe"

**Comment by rarebkcat** [comment]
It's in this section: https://rbms-bsc.github.io/DCRMR/docs/General-Rules/Transcription/#table-of-contents

**Comment by rarebkcat** [comment]
Or, in the code, here: https://github.com/rbms-bsc/DCRMR/blob/master/_pages/General-Rules/Transcription.md#table-of-contents

**Comment by ladylazarus3** [comment]
i think issue [issue 6](https://github.com/rbms-bsc/DCRMR/issues/6) entitled "Referencing particular lines in issues" may have also solved this issue.  i've added a temporary anchor point in the Transcription guidelines to illustrate the way we can have folks reference individual instructions within the text (example of a link to an anchor: https://rbms-bsc.github.io/DCRMR/docs/general-rules/Transcription#GR.5).  

Should this issue be closed for now?
