### ISSUE TITLE
Instruction: multiple statement of responsibility relating to edition

### ISSUE THREAD

**Issue by mjmascaro** [rbms-bsc/DCRMR#50]
In the DCRMR draft text for Statement of responsibility relating to edition a new instructions were added for "[More than one designation of edition and more than one statement of responsibility relating to edition](https://docs.google.com/document/d/1juWF_PhS9YZP-M-MGTflUPjfrS2YZt7BKNzyZx---DQ/edit#bookmark=id.xv8wu5zghhzh) " that were not in original DCRM(B) or RDA.  Debating whether this instruction is needed.  (General rule for statement of responsibility relating to edition says to "Follow the instructions in X.X. (statement of responsibility relating to title proper)  for the transcription of such statements," which I think covers the same ground.

**Comment by elizhobart** [comment]
Outcome of August 12 meeting: We will remove this instruction.
