### ISSUE TITLE
Referencing particular lines in issues

### ISSUE THREAD

**Issue by rbms-bsc** [rbms-bsc/DCRMR#6]
However, when I made it an md file, I couldn't create a new issue directly from code -- I don't think the .md file supports it; the _config.yml file does, as does a file without an extension.

_Originally posted by @rbms-bsc in https://github.com/rbms-bsc/DCRMR/issues/4#issuecomment-630846326_

**Comment by rbms-bsc** [comment]
In #4, I created a new file to see when I could create an issue from code and when I couldn't. My conclusion is that you can't create an issue from code in a .md file, which is what we're using.

Therefore, we're going to need to figure out how to reference particular parts of the code in issues, especially for typos and the like, where we need to zero in on a particular place.

**Comment by ladylazarus3** [comment]
we could use the citation anchors in the text itself?  For example, here is a URL that links to a specific instruction:
https://rbms-bsc.github.io/DCRMR/docs/title/Title-proper/#1.1A4.3

**Comment by rarebkcat** [comment]
That could work, especially since I anticipate us using a permalink for each section. 

Link to the typo I introduced is here: https://rbms-bsc.github.io/DCRMR/docs/General-Rules/Transcription/#table-of-contents

**Comment by dcrmr** [comment]
Current best practices for adding links between DCRMR webpages has been added to the [DCRMR Wiki "how to" documentation](https://github.com/rbms-bsc/DCRMR/wiki/DCRMR-Editorial-Guidelines)
