### ISSUE TITLE
Related elements 

### ISSUE THREAD

**Issue by flapka** [rbms-bsc/DCRMR#63]
Do we want to establish a protocol for referencing related elements? (Or if we have already, could someone bring me up to speed?)

There are at least three possible places to make such references:

1. Definition and scope: We used this technique a fair bit in pre-3R drafts ([example](https://docs.google.com/document/d/1uf-fbjFNT8wgxdIyvUfJHMY9gihsyEy-xDSfVspJ-lI/edit#bookmark=id.ddkdw0knfgsq)), but I think we've moved away from it now.

2. In the body of instructions ([example](https://docs.google.com/document/d/1oDh0kBldgYEUXA5kny4WIbsS1RYTJmECM-vIVMYH-6w/edit#))

3. At end of instructions, in the style of Beta RDA ([example](https://docs.google.com/document/d/1JSf-40uCef9J2DL9e39146yMejO84KI92EpSADEgnYY/edit#bookmark=id.5gnyap147m84))

I think we probably want to keep *2*, when such references occur naturally in the flow of instructions. Probably we don't want instances of both 1 and 3.

**Comment by lizoknj** [comment]
I agree that see references at the top of the page are more visible, but sometimes you have a better idea of whether you need to go somewhere else after you have gone through the whole document and confirmed that what you want isn’t there.  

Should the list of see references, whether at the top or at the bottom, include see references that also appear in the text of instructions? It is repetitive, but if someone just scans the list quickly, they will miss the links that are integrated in the instructions.

**Comment by mjmascaro** [comment]
Thanks, Francis for bring this issue up.  I agree that we want to keep 2 and should pick between 1 and 3.  (I think I lean towards 1).

As to Liz's question, I am not sure all the elements references used within the body of the text warrant being on an element reference list.  (I am thinking of all the cross reference to note elements).  Perhaps scope the element reference list to cases where there is some ambiguity from the element name where information should be recorded. (I think custodial history/ modification of item is a prime example).  In those cases, the related element would always appear on the reference list (either in the scope section or end) and if it makes sense for flow (or to call out a specific situation) it would be not prohibited to reference that element again inline with the text.

**Comment by elizhobart** [comment]
Outcome of September 2 meeting: Group expressed preference for 1 and 2. An additional issue was raised as to which related elements should be named in the scope. We will open a new GitHub issue to continue that discussion.
