### ISSUE TITLE
Prescribed punctuation

### ISSUE THREAD

**Issue by elizhobart** [rbms-bsc/DCRMR#64]
Due to the variation that will be introduced by guidelines for minimal punctuation, we'd previously discussed moving all instructions for prescribed punctuation to the [preliminaries](https://rbms-bsc.github.io/DCRMR/general-rules/Prescribed-punctuation/). Currently, we've been retaining a prescribed punctuation section in chapter pages with a link to the associated instructions in the preliminaries (see [series](https://rbms-bsc.github.io/DCRMR/series/), for example). However, this approach skips the introductory paragraph, which instructs catalogers to use their local policy, so we'll need to rethink this.

I see three potential solutions:

1. Omit the "prescribed punctuation" section from chapter pages
2. Retain the instruction and link as is, but phrase as, "If applying prescribed punctuation, see..."
3. Retain the instruction, but link to the top of the "prescribed punctuation" page.

My preference is #1. As the PCC guidelines for minimally punctuated records are more widely adopted, this section will be references less frequently (and admittedly, I'm not sure it's frequently used now). For those who do need this information, it's findable in the left-hand navigation bar. However, I wanted to open this up to broader discussion. What do you all prefer?

**Comment by lizoknj** [comment]
I prefer no. 1; second choice no. 2

**Comment by elizhobart** [comment]
Thanks, everyone. Based on discussion, I am going to ask that we remove prescribed punctuation from the chapter pages and just leave it in the preliminaries/left-hand navigation. This section will apply to fewer and fewer people moving forward and I don't feel it's necessary to give it such prominence on the chapter page. It should be sufficient to include in the preliminaries for those who do need it.

@ladylazarus3, could you make this change in the chapter template?

**Comment by ladylazarus3** [comment]
Hey there,  apologies for the late reply.  i'm getting back in the library saddle.  

i've updated the [chapter template](https://github.com/rbms-bsc/DCRMR/wiki/Template:-Chapter-Template-for-DCRMR).  Does this look right to you all and meet expectations?  Let me know if it needs any additional tweaking.  Does it need anything else?  Are any sections missing?

If this looks right, i'll circle back to the drafted chapter pages and make sure the changes are reflected there as well.  Many of these chapter level pages are still pretty bare bones and are underdeveloped, so it should be a pretty quick tweak (e.g. [edition chapter page](https://rbms-bsc.github.io/DCRMR/edition/) ).

kalan

**Comment by elizhobart** [comment]
Thanks, kalan! (And no worries; one day is not late in my book!)

The chapter template looks good to me! Right now, I'm not seeing anything missing. I think we're good to go as is.
