### ISSUE TITLE
Forbidding transcription of omitted text in notes

### ISSUE THREAD

**Issue by deborahjleslie** [rbms-bsc/DCRMR#76]
From https://github.com/rbms-bsc/DCRMR/wiki/DCRMR-Editorial-Guidelines:

> In DCRMB4, there are several instructions that state if it is too numerous to exhaustively list all values of an elements that you can omit some using the mark of omission, and then give the option that the omitted values can be transcribed, in a note, if considered important. Omit these note options from DCRMR rewrite, under the rationale that for well formed data if the information is considered important is [sic] should be recorded in the element proper.

 
Neither Jessica, who is working with me on chapters 1-2, nor I remember the discussion behind this decision. It is problematic for several reasons. First, as a general principle, we should not be forbidding notes of any kind. Second, the result in records for early printed materials is counterproductive. There are excellent reasons for abridging very long titles, for example—readability on a screen—accompanied by the intent to include the full text in keyword searches. I'd also like to point out that "Note on title" is a proper element. 

Thoughts?

**Comment by mjmascaro** [comment]
As a little bit of background, this specific editorial decision was made during the DCRM Task Force's writing of the draft policy statements and carried over into DCRMR, under the principle we would not revisit every editorial decision made by the DCRM Task Force.  

I also agree as a general principle we should not be forbidding specific notes, but I think not specifically giving instructions on a particular note is different from forbidding.  (As said in DCRM(B) 7A1.2 "Notes, by their nature, cannot be enumerated exhaustively...") Forbidding would be an instruction that says do not make note X, which is not the case here.    

For well formed data, I think we should be strongly encouraging that full transcription is transcribed in the element proper and not splitting part of it into a note.  For that reason, I agree with this editorial decision.  

 (I am sure this particular topic will spark quite a bit of discussion during community review.)

**Comment by elizhobart** [comment]
I agree with Michelle. These notes aren't forbidden; we just aren't specifically calling it out. In addition, I also agree that we should generally be encouraging transcription in the element proper, which is better for data and searching.

**Comment by ladylazarus3** [comment]
my concern with transcribing omitted text as part of another element stems from the considerations about how Linked Data is indexed and queried.  SPARQL and RDF statements are very different beasts than SQL and relational databases.  At this point, we don't know how the RDF data that we produce would be indexed and what the triple store would look like.  RDA takes a lot of the technical requirements of Linked Data and assumptions surrounding application profiles on faith.  And that worries me.  Greatly.

There is lots of retrospective data out there with omitted text transcribed as notes... so maybe this is a null point... but i just think we should strive to make the data less complex and more predictable in any way we possibly can by putting the data in an element where folks would expect to query it.   

We could add it as an option, if folks think that is best, but i just don't trust SPARQL to do the magic we want it to do here.

**Comment by elizhobart** [comment]
Thanks for the feedback, everyone. I would like to leave these instructions as is. Our instructions do still allow for recording this information as part of a note if deemed important, although they don't explicitly say that. @ladylazarus3 raises the important point that, due to indexing and querying, it's better to record this information as part of the main field wherever possible. Because of that, I am happy to leave recording omitted information in a note as an option <i>without</i> explicitly mentioning it in the note text.

**Comment by deborahjleslie** [comment]
I can live with the decision, but would like to address the arguments advanced in favor of it. One of the things I appreciate about RDA is that despite its wild departure in structure from AACR2, the output for ordinary library cataloging is pretty much the same.  

What concerns me about the well-formed data argument is the intent to change the outcome of a catalog description in order to conform to a data model and demands, but at the expense of other functions of the catalog record. A large block of text not only takes up valuable screen real estate, but is hard to read. More isn't always better, and given the importance of a title for identification, a large block of transcribed usually obscures what's important. 

Models and practice are rapidly evolving, and there are possibilities down the road to reconsider them. For example, we don't really have a plan for "manifestation statements." I can envision the day when our metadata description sets will be hierarchically interconnected as they are in RIMMF, where work and expression statements take on more of the load for identification. We're not there yet and may not be for some time.

**Comment by elizhobart** [comment]
Thank you, Deborah. I am going to mark this issue as "closed." However, I am taking note of your concerns and will keep them in mind as we move forward into public review and revisions. We can revisit if we get feedback related to this issue.
