### ISSUE TITLE
in-text references to other elements - style question

### ISSUE THREAD

**Issue by rarebkcat** [rbms-bsc/DCRMR#78]
Hi, all—
 
A stylistic question came up that kalan and I couldn’t find a definitive answer to: are we capitalizing in-text references to other elements or not?
 
For example:
 
Record additional information that applies to all exemplars of the manifestation or particular groups of exemplars of an edition or issue as a [note on carrier](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-carrier/) (see [5.233.3.1](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-carrier/#5.233.3.1)). Record information pertaining to individual items as a [modification of item](https://rbms-bsc.github.io/DCRMR/notes-on-items/Modification-of-item/) (see [8.21.X.X](https://rbms-bsc.github.io/DCRMR/notes-on-items/Modification-of-item/#8.21.X.X)).
 
OR
 
Record additional information that applies to all exemplars of the manifestation or particular groups of exemplars of an edition or issue as a  [Note on carrier](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-carrier/) (see [5.233.3.1](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-carrier/#5.233.3.1)). Record information pertaining to individual items as a [Modification of item](https://rbms-bsc.github.io/DCRMR/notes-on-items/Modification-of-item/) (see [8.21.X.X](https://rbms-bsc.github.io/DCRMR/notes-on-items/Modification-of-item/#8.21.X.X)).
 
In both instances, “note on carrier” and “modification of item” will be hyperlinks.
 
Post-3R RDA does not capitalize the element names, although they often precede the element with the RDA entity, which is capitalized (for example, from [extent of manifestation](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-8754c7a9-c38c-3735-9cf9-865df717f81b) “The carrier is not in the list at Manifestation: [carrier type](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-0dd63c0d-066f-3ddc-885a-ff83c25cf752)”).
 
Currently, more are in-text references to other elements are lowercase than uppercase, but, no matter the decision, there’s going to have to be some editing to bring everything into alignment.
 
Whichever decision we make, we’d like to go ahead and record it in the Editorial Wiki for future reference.
 
Thanks,
Amy and kalan

**Comment by lizoknj** [comment]
I started out capitalizing element names within the text, but then converted them to lowercase when I noticed that lowercase predominated. For what it's worth, in the Beta Toolkit the name of each element appears in lowercase at the head of the page devoted to that element, and within the list of elements belonging to an entity type. I would be more in favor of capitalizing the first word of the element name if we weren't using a distinctive font for element names, but since we are, that's not an issue.

**Comment by elizhobart** [comment]
Outcome of September 2 meeting: There was a general preference for capitalizing the first word of the element. I am leaving this issue open for now to collect any additional comments since we ran out of discussion time.

**Comment by jess-grz** [comment]
As many already mentioned in the meeting, I don't think we need to be beholden to RDA for this style issue. (And we already noted inconsistencies in capitalization in RDA anyway.) I support capitalizing the first word in the element. The capitalization + hyperlink is a clear signal that the text refers to another element. I view each element page as a document in its own right with the element name also acting as a title. Stylistically speaking (in addition to adding clarity), it would be appropriate to capitalize.

**Comment by ladylazarus3** [comment]
Just a quick question (since i just ran into it), would we also capitalize the name when it is referring to the element in plural?

(for example:  Edition statement and Edition statements vs. edition statement and edition statements)

and ergo, we are envisioning every instance of 'Edition statement' to be hyperlinked, correct?

kalan

**Comment by elizhobart** [comment]
I don't think that every instance needs to be hyperlinked, though I'm having trouble deciding where the line would be. In general, I'd say the first instance of an element in an instruction should be capitalized and hyperlinked, but if the same element is referred to multiple times, maybe just the first one? I'm not sure if that's a situation that arises or not. For the plural question, could you provide the whole sentence where that appears? It would be helpful for me to see context.

**Comment by ladylazarus3** [comment]
Sure thing, here is a very rough draft of [Note on edition statement](https://rbms-bsc.github.io/DCRMR/edition/Note-on-edition-statement/#3.29.7.1) and the its [googledoc](https://docs.google.com/document/d/116MuEc6XRc7DE6kGh2bDVFzNY4JIPvmad89Y7exFD08/edit)

**Comment by elizhobart** [comment]
Thanks, kalan! I this we'll definitely want to capitalize the first letter any time we've hyperlinked the element, whether singular or plural. It looks a little odd to me to see the non-hyperlinked statements capitalized. With 3.29.7.1 as an example, to me, it would read better as "Make a note on edition statement of differences in edition statements ..." but "relating to parts as an in Note on item" (since "Note on item" is hyperlinked.

What do others think?

**Comment by ladylazarus3** [comment]
i slept on it... tell ya folks what, i'll go head and capitalize all hyperlinks at this juncture, we can always go back and adjust other capitalization or add hyperlinks as needed at a later point. 

i think this capitalization quandary might be a symptom of a flaw in the heart of the conceptual model.  Is a 'statement of responsibility' actually an attribute (This is a thing of a Thing.) or is it a 'Statement of responsibility' (This is a Thing.)?   Does a statement of responsibility still exist without its manifestation?  [rhetorical questions, please don't answer.  There is a good reason i'm not an ontologist ;)] 

Of all the books we've lost throughout the centuries and only have proof of their existence through the descriptions in other works and bibliographies means my heart screams, 'Yes, it is a Statement of responsibility!'  In any instance and all abstractions aside, i like the capitalization of the hyperlinks.

kalan (proudly, a thing of a Thing)

**Comment by rarebkcat** [comment]
I agree with kalan re: the slippage in the conceptual model.

I do agree we want to capitalize in the case of plurals, (for example, "make Variant titles (see X.X.X.X)").

As a rule of thumb, I'm happy with a hyperlinked element is capitalized; a non-hyperlinked reference is not. Generally, we've tended to hyperlink heavily, so we'll have more hyperlinked than not. (In the example you give, Elizabeth, this would be incredibly recursive as we're in the instructions for Note on edition statement!)
