### ISSUE TITLE
Notes chapters

### ISSUE THREAD

**Issue by elizhobart** [rbms-bsc/DCRMR#89]
Amy and kalan are working on numbering, and a question arose regarding the notes chapters. Currently, our text order includes separate chapters for "other notes" and "notes on items." Increasingly, it looks like the "other notes" chapter will include sections on notes on work, notes on expressions, and notes on manifestations. With this new structure, it makes sense to fold "notes on items" into the same chapter, rather than having it as a separate chapter. However, since we've been planning on two separate chapters, I wanted to get buy-in before making this decision. Does it make sense to combine the two note chapters? Or should we leave them separate?

**Comment by ladylazarus3** [comment]
i gotta say, i really love the idea of combining the [Other notes](https://rbms-bsc.github.io/DCRMR/other-notes/) and [Notes on items](https://rbms-bsc.github.io/DCRMR/notes-on-items/) chapters.  Structurally, it solves a lot of problems that have been giving me a headache at the chapter-level and the organization of the various Note elements via a WEMI-like structure makes a lot of logical sense, is easy to teach to folks, and reinforces the WEMI model in a way that folks see it and interact with it daily via the manual.  

i absolutely enthusiastically support this change.

**Comment by rarebkcat** [comment]
A specced out version of a new Notes chapter, with citation numbering per the [Citation numbers (draft)](https://github.com/rbms-bsc/DCRMR/wiki/Citation-numbers-(draft)), would look something like this:

Citations are created based on the element's domain (“The RDA entity that is described by an element”). I ordered them based on the Order of the text spreadsheet.

Chapter 9 - Notes
9.1_ - notes on works
9.2_ - notes on expression
9.3_ - notes on manifestation
9.4_ - notes on item

9.05 Note on RDA entity - RDA entity

9.1 Note on work -- work
9.12 Dissertation or thesis information - work (superelement)
9.121 Academic degree - work
9.122 Degree granting institution - work
9.123 Year degree granted - work

9.2 Note on expression -- expression
9.25 Summarization of content - expression

9.3 Note on manifestation -- manifestation                                                                                                                                                    
9.31 Accompanied by manifestation  -- manifestation  
9.32 Manifestation dissertation statement -- manifestation
9.33 Manifestation described in - manifestation
9.34 Supplementary content - manifestation
9.35 Issued with - manifestation

9.4 Note on item - item
9.41 Modification of item - item
9.42 Custodial history of item - item
9.43 Note on extent of item -- item
9.44 Note on dimensions of item -- item
9.45 Bound with - item

**Comment by io-uk** [comment]
Combining the two chapters is fine with me. As notes on specific elements are within the chapters for the specific elements, should the heading for the combined chapter 9 be "Other notes", "Additional notes" or something similar to make clear that it doesn't contain all the notes?

**Comment by rarebkcat** [comment]
I like Additional notes, i think, although I don't feel strongly about it.

**Comment by jess-grz** [comment]
I strongly support combining "Other notes" and "Notes on items," especially if this combined chapter is structured in WEMI order. At this point, many catalogers (at least those familiar with DCRM and AACR2) are used to seeing a notes chapter. It's a great solution for notes that don't fit perfectly into element-specific chapters or that would interrupt the flow of the "main" text. I'm also leaning more toward "Additional notes" as the chapter title, but I don't have a strong preference.

**Comment by elizhobart** [comment]
Thanks, everyone. Unless we hear anything to the contrary by end of business today, we will merge these into a single chapter. I am also in favor of "Additional notes" as the title.

**Comment by dcrmr** [comment]
Outcome: notes will be merged into a single chapter with title, Additional notes.
