### ISSUE TITLE
*Issued with* questions

### ISSUE THREAD

**Issue by flapka** [rbms-bsc/DCRMR#9]
I have multiple questions concerning the *issued with* element (our [gdoc](https://docs.google.com/document/d/1YVu7GaVV_l3WzeYNPDnpPYd2nLcpvGx_k8FGf9q9Qno/edit) | [RDA  beta](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-f9305084-ad80-3d9e-8c28-e649bb4f5500)). 

1. In RDA, the specified range for this element is a Manifestation. If that's the case, is it still kosher to reference multiple manifestations as our guidelines suggest (in the manner of a 501 note)? FWIW, the BIBFRAME [issuedWith](http://id.loc.gov/ontologies/bibframe.html#p_issuedWith) property presents a similar issue -- with range = Instance. 

2. With this element, we tell people to go elsewhere to record information for bound withs or for content notes (e.g. if the pagination is continuous). My inclination is to provide such info as an elaboration on scope. Would others do the same?

3. In 2017, MARC created the 777 field to record issued with relationships as access points. According to RDA Element Reference, an issued with in the 501 is an unstructured description, in the 777 a structured description. Are we okay with that?

3a. Is there any desire to revise our guidance to distinguish between issue with data as transcribed information (501?) versus issue with data as an access point (777). Our current practice seems to muddy those two methods (e.g. by beginning with the main entry).

**Comment by flapka** [comment]
Discussed question 2 in the finalizing group meeting on 5/26/2020. Agreed to DCRMR elaboration on RDA's definition and scope.

Questions 1 and 3 deferred until later.

**Comment by mjmascaro** [comment]
1. I see your point.  This is may not be the correct way to think about it, but I tend to think of each manifestation listed within 501 as silently repeating the element.   Though looking at MARC documentation, 501 is repeatable and repeating the element would be cleaner for future MARC->BibFrame conversion.

3.  I agree that our current practice muddies the two recording methods and I think is closer to access point than unstructured description.  Based on Beta Toolkit instructions, if using the [unstructured description method ](https://beta.rdatoolkit.org/en-US_ala-f9305084-ad80-3d9e-8c28-e649bb4f5500) we would only record the title, which I do not think is desirable.  

I guess the broader question is whether we think RDA Element MARC mapping is entirely correct.  Gordon Dunsire has repeated said that all current RDA practices will be permissible under the new Toolkit and our current practice of recording structured description in the 501 is supported by LC-PCC PS 28.1.1.3.  Whether institutions prefer to use the 501 or 777 (or both) for issued with will be dependent on how their systems handle the situation.   So I think I am leaning towards not being prescriptive on which field to use.

**Comment by flapka** [comment]
Thanks Michelle, I'm persuaded by your thoughts to leave these sections as drafted (low fuss). Unless others want to dive further, let's consider resolved.

One more suggestion: Might it make sense to revise the "With:" formulation that begins the note to "Issued with:" to be consistent with RDA and BIBFRAME terminology?

**Comment by flapka** [comment]
The group endorses the idea of changing to "Issued with" as the preliminary phrase.

**Comment by mjmascaro** [comment]
Resolved during Text Finalizing Group meeting June 2, 2020. Will stick with current text draft which follows DCRM(B) instructions of structured note.
