### ISSUE TITLE
Citation numbering and a minimum viable product 

### ISSUE THREAD

**Issue by deborahjleslie** [rbms-bsc/DCRMR#94]
In order to produce a minimum viable product in the process of splitting and recombining title and statement of responsibility elements, @jess-grz, @lizoknj and I are flagging certain sections that should be eliminated or integrated elsewhere for future work. The question arises, however, as to what that does with document numbering. How rigid or flexible is the numbering within a section/chapter intended to be? 

For example, in DCRM(B) there is a separate section (1G) on single-sheet manifestations, following instructions for statement of responsibility, dealing mostly but not entirely with choosing title proper. Fine, we moved them as a block over to [Title proper](https://docs.google.com/document/d/15lO3mzxfhCy9dBJDh7izEkB6SNL99LVn2W06BC5QAk8/edit#). (There's one problematic paragraph but we've marked it.) Is there sufficient difference in principle between how single sheets are treated from other printed text, aside from the fact that the whole sheet is the preferred source of information? It's just that single sheets are more likely not to have a title &c. than codexes. We believe the instructions ought to be integrated into their proper elements, but that would involve substantive re-writing and so not appropriate for a MVP. Do we need to worry about numbering?

**Comment by elizhobart** [comment]
No need to worry about numbering for now. Our numbering scheme is designed to be flexible so that sections can be added or removed without doing damage to the text as a whole. kalan had the brilliant idea to use decimals instead of whole numbers, which will make it very easy to insert instructions. 

We do want to be careful not to re-use numbers if an instruction is removed, which was a problem in earlier iterations of RDA. At some point, we'll have to decide how best to track "retired" numbers, but we can cross that bridge a little later since our numbers aren't set in stone yet.

**Comment by ladylazarus3** [comment]
Yes, the [citation documentation](https://github.com/rbms-bsc/DCRMR/wiki/Citation-numbers-(draft)) is solid (many thanks to the wonderful @rarebkcat!), but the citation schema itself is fluid and extensible via the decimals, but we understand the current citations within DCRMR are going to change (and especially with the merging of the Other Notes and Notes on items chapters-- they have to change).  

Citations are just serving as steady anchor-points for us now.  A few new instructions have been very helpfully added through the internal review / errata process (e.g. [Type of binding](https://docs.google.com/document/d/1mb67GUCT1bbQjywyeTpbjpWDe5iymT3qJ7jeoof5Ra4/edit#heading=h.h3k3xkiv9x9v) thanks, @lizoknj!) and citation renumbering has taken place as needed throughout the entire MVP development cycle.

Notepad++ allows for global changes in numbering which will feature heavily in managing this citation numbering work.  If we can get all the pieces in text in place where we want 'em (and the sooner the better), the easier that eventual renumbering process will be.

Other methods that might help us (eventually) track retired numbers is that the webpage has a built-in blog feature that we can highlight editorial and development changes in, GitHub has built-in versioning processes, etc.  We do need to cross that  bridge, but for now, the numbers aren't set in stone.

k
